### ISSUE TITLE
List VATSIM Events in Qutescoop

### ISSUE THREAD

**Issue by FX5F** [qutescoop/qutescoop#117]
Hi,

there is an JSON list with all Events from the VATSIM event calendar available.
https://my.vatsim.net/api/v1/events/all

I would be cool if these event would be listed in Qutescoop for example like ATC Bookings, so that you can see where today will be an event.
Maybe even mark airports which currently have an active event (also in the time warp).

**Comment by jonaseberle** [comment]
Hi @FX5F, that sounds interesting.
Do you want to make a scribble or drawing how that info could be presented?

**Comment by jonaseberle** [comment]
I am struggling to think of a good way to represent this information.

I think the way https://vatsim.net/events/ shows events (chronologically and ALL future events on the map) is good to look for interesting events. But that does not fit well to QuteScoop's "Situation at a certain time"-approach.

I'll close this for now. Please reopen if you feel like it.
