### ISSUE TITLE
Improve Booked ATC dialog

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#119]
Hi,

"Booked ATC" list by default sorts by Callsign **descending**, which makes no real sense. Could we a) change the default sorting to be **ascending**, and perhaps even remember the last sorting chosen in config?

Best regards,
Daniel

**Comment by jonaseberle** [comment]
I would rather sort by "From" ascending:
![image](https://user-images.githubusercontent.com/1678001/156816832-276e48bc-7088-4ded-8086-8c20a3d50bca.png)
What do you think? 

Saving sorting state can definitely be done if someone is up for it. We could also save table column widths and these newly added "panel splitter" positions
![image](https://user-images.githubusercontent.com/1678001/156817886-86de003b-50aa-47b1-897e-204451f84945.png)

**Comment by jonaseberle** [comment]
Oh, and opening the links when clicking on a line has become annoying since nobody adds the event URLs there any more ;) should be removed IMHO.

**Comment by droesen** [comment]
> I would rather sort by "From" ascending:
> ![image](https://user-images.githubusercontent.com/1678001/156816832-276e48bc-7088-4ded-8086-8c20a3d50bca.png)
> What do you think?

Not really... that scatters the info about a specific aerodrome around, doesn't fit _my_ way to check options. In the end I'm looking for "which ADs are how well staffed, and what's the core time when most/all controllers are online at that AD". This requires AD sorting.

**Comment by jonaseberle** [comment]
Ok. To be honest I rarely use that dialog but instead use Time Warp to plan my evening.
