### ISSUE TITLE
Controller info dialog resizing on 2nd and further clicks on station label

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#124]
Hi,

kinda weird effect: I'm looking at the map and clicking. e.g. on the "EDMM_G" center controller label to see his info:

![image](https://user-images.githubusercontent.com/63562075/157305979-b2b62ee1-0cd7-4490-b1ae-424c77931046.png)

Now I click a 2nd time onto the same "EDMM_G" label and the dialog resizes narrower:

![image](https://user-images.githubusercontent.com/63562075/157306023-d4a64dd6-5498-4f12-85dc-f740c56905df.png)

The dialog doesn't resize on any further clicks. To reproduce again, open some other controller's info dialog, then go back to EDMM_G (or any other), to see the effects of 2nd click on same station.

This is with v2.6.0 and the current test build for the ATC booking list sorting.

Best regards,
Daniel

**Comment by jonaseberle** [comment]
Yes, we let it choose its "preferred" size after we have updated the info in the dialog.
It is more noticeable in Pilot dialogs: With long routes or many flight plan remarks, this ought to make sure the dialog is big enough to show them.
Yet this does not work well on the first repaint. Thus we should try how it feels when we remove that function.

**Comment by jonaseberle** [comment]
I've removed the auto-resize in a test build.

It might occasionally lead to this:
![image](https://user-images.githubusercontent.com/1678001/157599540-c4cd5852-343a-4f8f-a55f-b652dd75da12.png)
but users can resize the dialog.

**Comment by jonaseberle** [comment]
@droesen could you help me get some insight how it is on Windows by testing https://github.com/qutescoop/qutescoop/pull/126 please?

**Comment by droesen** [comment]
Yeah, hoping to get to more VATSIM time this weekend. Will check out. Cursory check looks fine already.

**Comment by droesen** [comment]
From some limited testing time I found, "looks fine to me!"

**Comment by jonaseberle** [comment]
@droesen thank you for testing.
> In this last commit I have set Pilot and Controller dialog differently: The controller dialog is told to not shrink below optimum size. Let's compare and see which one works better.
Have you noted any difference between Pilot and Controller dialogs?

**Comment by jonaseberle** [comment]
@droesen did you see any difference between Pilot and Controller dialog on Windows?
