### ISSUE TITLE
Version 2.6.3 crashs on start macOS 12.3 (MacbookAir M1)

### ISSUE THREAD

**Issue by ansgar-hoffmann** [qutescoop/qutescoop#134]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               QuteScoop [44030]
Path:                  /Volumes/VOLUME/*/QuteScoop.app/Contents/MacOS/QuteScoop
Identifier:            com.yourcompany.QuteScoop
Version:               ???
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-03-24 17:58:57.7403 +0100
OS Version:            macOS 12.3 (21E230)
Report Version:        12
Anonymous UUID:        6BDF3472-24AD-5D74-32AA-1F7B50A24EAB

Sleep/Wake UUID:       A730059D-459A-48D4-9D91-EB3799A87186

Time Awake Since Boot: 180000 seconds
Time Since Wake:       110 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: @rpath/QtOpenGL.framework/Versions/5/QtOpenGL
Referenced from: /Volumes/VOLUME/*/QuteScoop.app/Contents/MacOS/QuteScoop
Reason: tried: '/private/var/folders/bm/1wg6fb_56cxfbm7t3n7n8d4c0000gn/T/AppTranslocation/C26A261F-1FB3-4315-8FA5-65F9BD7EE1EC/d/QuteScoop.app/Contents/MacOS/../Frameworks/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/Users/runner/work/qutescoop/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/private/var/folders/bm/1wg6fb_56cxfbm7t3n7n8d4c0000gn/T/AppTranslocation/C26A261F-1FB3-4315-8FA5-65F9BD7EE1EC/d/QuteScoop.app/Contents/MacOS/../Frameworks/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/Users/runner/work/qutescoop/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/Library/Frameworks/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/System/Library/Frameworks/QtOpenGL.framework/V
(terminated at launch; ignore backtrace)

Application Specific Information:
Library not loaded: @rpath/QtOpenGL.framework/Versions/5/QtOpenGL
Referenced from: /private/var/folders/bm/1wg6fb_56cxfbm7t3n7n8d4c0000gn/T/AppTranslocation/C26A261F-1FB3-4315-8FA5-65F9BD7EE1EC/d/QuteScoop.app/Contents/MacOS/QuteScoop
Reason: tried: '/private/var/folders/bm/1wg6fb_56cxfbm7t3n7n8d4c0000gn/T/AppTranslocation/C26A261F-1FB3-4315-8FA5-65F9BD7EE1EC/d/QuteScoop.app/Contents/MacOS/../Frameworks/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/Users/runner/work/qutescoop/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/private/var/folders/bm/1wg6fb_56cxfbm7t3n7n8d4c0000gn/T/AppTranslocation/C26A261F-1FB3-4315-8FA5-65F9BD7EE1EC/d/QuteScoop.app/Contents/MacOS/../Frameworks/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/Users/runner/work/qutescoop/Qt/5.15.2/clang_64/lib/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/Library/Frameworks/QtOpenGL.framework/Versions/5/QtOpenGL' (no such file), '/System/Library/Frameworks/QtOpenGL.framework/V

Thread 0 Crashed:
0   Rosetta Runtime Routines	       0x100db4940 ???
1   <translation info unavailable>	       0x100df6ce4 ???
2   dyld                          	       0x200f84212 abort_with_payload_wrapper_internal + 80
3   dyld                          	       0x200f84244 abort_with_payload + 9
4   dyld                          	       0x200f3276f dyld4::halt(char const*) + 375
5   dyld                          	       0x200f2e5a5 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 3995
6   dyld                          	       0x200f2d4d4 start + 388

Thread 1:: com.apple.rosetta.exceptionserver
0   runtime                       	    0x7ff7ffcb49a4 0x7ff7ffcb0000 + 18852
1   runtime                       	    0x7ff7ffcc2738 0x7ff7ffcb0000 + 75576
2   runtime                       	    0x7ff7ffcc3ed0 0x7ff7ffcb0000 + 81616

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x0000000305a369c0   x3: 0x00000000000000da
    x4: 0x0000000305a365c0   x5: 0x0000000000000000   x6: 0x0000000305a365b0   x7: 0x0000002000f2ad87
    x8: 0x0000000305a365c0   x9: 0x0000000000000000  x10: 0x00000000000000da  x11: 0x0000000305a365c0
   x12: 0x00000000000000da  x13: 0x0000000305a369c0  x14: 0x0000000000000001  x15: 0x0000000000000006
   x16: 0x0000000000000209  x17: 0x0000000000000000  x18: 0x8000000108e1db70  x19: 0x0000000100daa000
   x20: 0x00000000000007ff  x21: 0x0000000108e22fa0  x22: 0xffffffffffffffff  x23: 0x0000000100db4914
   x24: 0x0000000200f84212  x25: 0x0000000100db41f4  x26: 0x0000000100df5388  x27: 0x0000000000000000
   x28: 0x0000000200f6e0de   fp: 0x000000002c000000   lr: 0x0000000100df6ce4
    sp: 0x0000000108e1db70   pc: 0x0000000100db4940 cpsr: 0x80001000
   far: 0x00000001093dc010  esr: 0x56000080  Address size fault

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???
       0x200f28000 -        0x200f93fff dyld (*) <dd9e80de-fb3b-349b-96a4-46874ad34d11> /usr/lib/dyld
    0x7ff7ffcb0000 -     0x7ff7ffcdffff runtime (*) <24497be3-a1b4-360a-b90e-cde9ce78a93b> /usr/libexec/rosetta/runtime

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=2772K resident=0K(0%) swapped_out_or_unallocated=2772K(100%)
Writable regions: Total=155.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=155.2M(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Rosetta Arena                     4096K        2 
Rosetta Generic                    764K      188 
Rosetta IndirectBranch              32K        1 
Rosetta JIT                      128.0M        1 
Rosetta Return Stack                20K        2 
Rosetta Thread Context              20K        2 
Stack                             8176K        1 
Stack Guard                       56.0M        1 
VM_ALLOCATE                       13.3M        5 
VM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)
__DATA                             176K        7 
__DATA_CONST                        80K        1 
__LINKEDIT                         608K        8 
__TEXT                            2208K        4 
dyld private memory               1024K        1 
mapped file                        6.0G       28 
===========                     =======  ======= 
TOTAL                              6.3G      253 
TOTAL, minus reserved VM space     6.3G      253 

-----------
Full Report
-----------

{"app_name":"QuteScoop","timestamp":"2022-03-24 17:58:57.00 +0100","app_version":"","slice_uuid":"06d1b7bb-f4db-3bc5-8954-2d68ac7938ce","build_version":"","platform":1,"bundleID":"com.yourcompany.QuteScoop","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 12.3 (21E230)","incident_id":"29B71C4D-784C-4F37-9B81-871B07215EC0","name":"QuteScoop"}
{
  "uptime" : 180000,
  "procLaunch" : "2022-03-24 17:58:55.5940 +0100",
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookAir10,1",
  "procStartAbsTime" : 4478559458565,
  "coalitionID" : 19622,
  "osVersion" : {
    "train" : "macOS 12.3",
    "build" : "21E230",
    "releaseType" : "User"
  },
  "captureTime" : "2022-03-24 17:58:57.7403 +0100",
  "incident" : "29B71C4D-784C-4F37-9B81-871B07215EC0",
  "bug_type" : "309",
  "pid" : 44030,
  "procExitAbsTime" : 4478610849002,
  "translated" : true,
  "cpuType" : "X86-64",
  "procName" : "QuteScoop",
  "procPath" : "\/Volumes\/VOLUME\/*\/QuteScoop.app\/Contents\/MacOS\/QuteScoop",
  "bundleInfo" : {"CFBundleIdentifier":"com.yourcompany.QuteScoop"},
  "storeInfo" : {"deviceIdentifierForVendor":"61B8725F-94D9-5C22-B6BA-F5C92E4EA304","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.yourcompany.QuteScoop",
  "crashReporterKey" : "6BDF3472-24AD-5D74-32AA-1F7B50A24EAB",
  "wakeTime" : 110,
  "sleepWakeUUID" : "A730059D-459A-48D4-9D91-EB3799A87186",
  "sip" : "enabled",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: @rpath\/QtOpenGL.framework\/Versions\/5\/QtOpenGL","Referenced from: \/Volumes\/VOLUME\/*\/QuteScoop.app\/Contents\/MacOS\/QuteScoop","Reason: tried: '\/private\/var\/folders\/bm\/1wg6fb_56cxfbm7t3n7n8d4c0000gn\/T\/AppTranslocation\/C26A261F-1FB3-4315-8FA5-65F9BD7EE1EC\/d\/QuteScoop.app\/Contents\/MacOS\/..\/Frameworks\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/Users\/runner\/work\/qutescoop\/Qt\/5.15.2\/clang_64\/lib\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/private\/var\/folders\/bm\/1wg6fb_56cxfbm7t3n7n8d4c0000gn\/T\/AppTranslocation\/C26A261F-1FB3-4315-8FA5-65F9BD7EE1EC\/d\/QuteScoop.app\/Contents\/MacOS\/..\/Frameworks\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/Users\/runner\/work\/qutescoop\/Qt\/5.15.2\/clang_64\/lib\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/Library\/Frameworks\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/System\/Library\/Frameworks\/QtOpenGL.framework\/V"]},
  "asi" : {"dyld":["Library not loaded: @rpath\/QtOpenGL.framework\/Versions\/5\/QtOpenGL","Referenced from: \/private\/var\/folders\/bm\/1wg6fb_56cxfbm7t3n7n8d4c0000gn\/T\/AppTranslocation\/C26A261F-1FB3-4315-8FA5-65F9BD7EE1EC\/d\/QuteScoop.app\/Contents\/MacOS\/QuteScoop","Reason: tried: '\/private\/var\/folders\/bm\/1wg6fb_56cxfbm7t3n7n8d4c0000gn\/T\/AppTranslocation\/C26A261F-1FB3-4315-8FA5-65F9BD7EE1EC\/d\/QuteScoop.app\/Contents\/MacOS\/..\/Frameworks\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/Users\/runner\/work\/qutescoop\/Qt\/5.15.2\/clang_64\/lib\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/private\/var\/folders\/bm\/1wg6fb_56cxfbm7t3n7n8d4c0000gn\/T\/AppTranslocation\/C26A261F-1FB3-4315-8FA5-65F9BD7EE1EC\/d\/QuteScoop.app\/Contents\/MacOS\/..\/Frameworks\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/Users\/runner\/work\/qutescoop\/Qt\/5.15.2\/clang_64\/lib\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/Library\/Frameworks\/QtOpenGL.framework\/Versions\/5\/QtOpenGL' (no such file), '\/System\/Library\/Frameworks\/QtOpenGL.framework\/V"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":1640188,"threadState":{"x":[{"value":6},{"value":1},{"value":12979497408},{"value":218},{"value":12979496384},{"value":0},{"value":12979496368},{"value":137454857607},{"value":12979496384},{"value":0},{"value":218},{"value":12979496384},{"value":218},{"value":12979497408},{"value":1},{"value":6},{"value":521},{"value":0},{"value":9223372041298762608},{"value":4309295104},{"value":2047},{"value":4444008352},{"value":18446744073709551615},{"value":4309338388},{"value":8606204434,"symbolLocation":80,"symbol":"abort_with_payload_wrapper_internal"},{"value":4309336564},{"value":4309603208},{"value":0},{"value":8606114014,"symbolLocation":10,"symbol":"__abort_with_payload"}],"flavor":"ARM_THREAD_STATE64","lr":{"value":4309609700},"cpsr":{"value":2147487744},"fp":{"value":738197504},"sp":{"value":4443986800},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":4309338432,"matchesCrashFrame":1},"far":{"value":4450009104}},"frames":[{"imageOffset":4309338432,"region":"Rosetta Runtime Routines","symbolLocation":10560,"imageIndex":0},{"imageOffset":4309609700,"region":"<translation info unavailable>","imageIndex":0},{"imageOffset":377362,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":80,"imageIndex":1},{"imageOffset":377412,"symbol":"abort_with_payload","symbolLocation":9,"imageIndex":1},{"imageOffset":42863,"symbol":"dyld4::halt(char const*)","symbolLocation":375,"imageIndex":1},{"imageOffset":26021,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":3995,"imageIndex":1},{"imageOffset":21716,"symbol":"start","symbolLocation":388,"imageIndex":1}]},{"id":1640233,"name":"com.apple.rosetta.exceptionserver","frames":[{"imageOffset":18852,"imageIndex":2},{"imageOffset":75576,"imageIndex":2},{"imageOffset":81616,"imageIndex":2}]}],
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  },
  {
    "source" : "P",
    "arch" : "x86_64",
    "base" : 8605827072,
    "size" : 442368,
    "uuid" : "dd9e80de-fb3b-349b-96a4-46874ad34d11",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 140703125143552,
    "size" : 196608,
    "uuid" : "24497be3-a1b4-360a-b90e-cde9ce78a93b",
    "path" : "\/usr\/libexec\/rosetta\/runtime",
    "name" : "runtime"
  }
],
  "sharedCache" : {
  "base" : 140703370117120,
  "size" : 15226814464,
  "uuid" : "71741bee-0abc-3e06-b329-770cac959b0c"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=2772K resident=0K(0%) swapped_out_or_unallocated=2772K(100%)\nWritable regions: Total=155.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=155.2M(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nRosetta Arena                     4096K        2 \nRosetta Generic                    764K      188 \nRosetta IndirectBranch              32K        1 \nRosetta JIT                      128.0M        1 \nRosetta Return Stack                20K        2 \nRosetta Thread Context              20K        2 \nStack                             8176K        1 \nStack Guard                       56.0M        1 \nVM_ALLOCATE                       13.3M        5 \nVM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)\n__DATA                             176K        7 \n__DATA_CONST                        80K        1 \n__LINKEDIT                         608K        8 \n__TEXT                            2208K        4 \ndyld private memory               1024K        1 \nmapped file                        6.0G       28 \n===========                     =======  ======= \nTOTAL                              6.3G      253 \nTOTAL, minus reserved VM space     6.3G      253 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "607844aa04477260f58a8077",
      "factorPackIds" : {
        "SIRI_MORPHUN_ASSETS" : "6103050cbfe6dc472e1c982a"
      },
      "deploymentId" : 240000066
    },
    {
      "rolloutId" : "5fc94383418129005b4e9ae0",
      "factorPackIds" : {

      },
      "deploymentId" : 240000287
    }
  ],
  "experiments" : [

  ]
}
}

Model: MacBookAir10,1, BootROM 7459.101.2, proc 8:4:4 processors, 8 GB, SMC 
Graphics: Apple M1, Apple M1, Built-In
Display: Color LCD, 2560 x 1600 Retina, Main, MirrorOff, Online
Memory Module: LPDDR4
AirPort: Wi-Fi, wl0: Feb  8 2022 01:44:45 version 18.60.21.0.7.8.126 FWID 01-1cdae627
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Air, Apple Inc.
Thunderbolt Bus: MacBook Air, Apple Inc.

**Comment by jonaseberle** [comment]
I wouldn't expect it to work on M1/ARM because we haven't explicitly built it for ARM.

Maybe you also have an idea for https://github.com/qutescoop/qutescoop/issues/48 (Related Mac-related discussion [de] in  https://board.vatsim-germany.org/threads/qutescoop-2022-vatsim-online-status-viewer-win-linux-mac.67817/).

I guess Mac users will currently have to build themselves until we come up with a better plan how to a) build and b) distribute so that users don't get silly warnings.

**Comment by Bartiefly** [comment]
Can you give us any pointers as to how to build the app ourselves? I can get past Gatekeeper, but the app still instantly crashes (Intel MacBook Pro here). The oldest version on here, 2.1.12, actually opens, but it doesn't work because Whazzup isn't supported by VATSIM anymore.

**Comment by jonaseberle** [comment]
@Bartiefly Using the Qt Creator is probably the easiest way. We use Qt 5.15

**Comment by Bartiefly** [comment]
@jonaseberle Thanks, unfortunately couldn't figure that one out, but did discover the Legacy VATSIM proxy tool, which allows the .json file to be converted to a Whazzup file, which means the old 2.1.12 can be used. Figured out a little Terminal sequence to hide the proxy .jar file to the background and everything is like it was :). Hopefully the issues with the 2.6.3 version will be sorted out at some point though, the new UI looks incredible. Thanks for all your hard work!

**Comment by jonaseberle** [comment]
I would need developers working with Mac to improve the situation. Sorry, can't do much.
I'll close in favor of https://github.com/qutescoop/qutescoop/issues/48
