### ISSUE TITLE
Route waypoints not shown [SOLVED]

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [qutescoop/qutescoop#135]
I have linked Qutescoop 2.6.3 (latest release from this week).

When showing the flightplan routes on the map, the correct trajectory is applied, but **none** of the labels of the route waypoints are displayed anymore, when zooming in.

- correct path to X-Plane 11/Custom Data is set
- checkmark set for "show fixes when zoomed in"
- have tried changing color and font
- have re-installed Qutescoop, including erasing Qutescoop settings from Windows registry and AppData-directory

Anything else that can be tested?

Will be away from home from tomorrow until next weekend.

**Comment by jonaseberle** [comment]
For me they are still showing:
![image](https://user-images.githubusercontent.com/1678001/160353312-4f9e27ac-693b-439c-9129-1a966004ce3b.png)

@FlyingFoxVATSIM It might be related to how many labels we are allowed to show - waypoint fixes have the 2nd lowest priority when rendering labels:
![image](https://user-images.githubusercontent.com/1678001/160354494-a79c370b-0167-4e5f-895d-ffe96ed6935f.png)

The setting "show fixes" does not affect showing route waypoints. It should *always* show all fixes/navaids, but currently doesn't. I opened [an issue](https://github.com/qutescoop/qutescoop/issues/136).

Have a great and safe trip!

**Comment by jonaseberle** [comment]
Oh, I had to look around for it myself... This actually toggles route waypoint labels:
![image](https://user-images.githubusercontent.com/1678001/160356869-567dae75-8ec5-448b-b3a6-577ad689e651.png)

**Comment by FlyingFoxVATSIM** [comment]
Back home and THAT was it! In all the years I had never used this menu-function, so it did not come to my mind to check the menus. Shame on me!!

Thanks for your help, case closed!

**Comment by diibify** [comment]
This is what the menu looks like under Windows. Unfortunately, you cannot see whether it is active or not. There is no checkbox or anything
![Waypoints](https://user-images.githubusercontent.com/16623471/161524668-1b880564-2e24-4978-914d-fe6936e2eef8.jpg)
.

**Comment by jonaseberle** [comment]
@diibify I think your OS style is using the icon color set to show the state.

Does it maybe use grayscale to show inactive and colors to show active?

That would be a bit unfortunate then. We could remove the icons or supply special icons for the "active" state.
![image](https://user-images.githubusercontent.com/1678001/161536825-06d04052-ff73-4729-af53-3f66ee7614a7.png)
But I don't see how we could force Windows to show the checkbox.

**Comment by diibify** [comment]
This may be due to my Windows 11 settings. I haven't changed anything in my colour set there. Whether I use the light or dark theme, I don't see any change in the menu. It works for @FlyingFoxVATSIM  (Windows 10) - see attachment
![Zwischenablage-1](https://user-images.githubusercontent.com/16623471/161543122-58e47822-6d10-44a7-bedb-bb4299e646a0.jpg)
.
