### ISSUE TITLE
Missing Northern border of LRBB and LUUU FIRs

### ISSUE THREAD

**Issue by tgpetrica** [qutescoop/qutescoop#142]
The Northern border of Romania (LRBB FIR) and Moldova (LUUU FIR) are missing.
![image](https://user-images.githubusercontent.com/57829402/176780508-23e859a9-2b8e-418c-ba5e-b58a5290e720.png)

**Comment by jonaseberle** [comment]
Hi Teodor,

this should be coming from https://github.com/qutescoop/qutescoop/blob/master/data/countries.dat which is just an unordered list of polygons.

I can see the Romian-Moldavian-Ukrainian border here so it is not a problem with the data:
![image](https://user-images.githubusercontent.com/1678001/176845766-a3d9e231-dcc4-4280-979c-7ab75a503b6c.png)

So it might be a problem with the graphics. Do you have missing country borders in other places, too?

**Comment by tgpetrica** [comment]
Hello Jonas,

No, I did not find another area where the border is missing. I tried to change the base map, no changes.

**Comment by jonaseberle** [comment]
Just for the record: Could you add under which OS/graphics card/graphics driver you see the problem?

**Comment by tgpetrica** [comment]
OS: Windows 10 Pro
Graphics card: Intel(R) Iris(R) Xe Graphics
Graphics driver: NVIDIA GeForce RTX 3030 Laptop GPU

**Comment by jonaseberle** [comment]
I can't reproduce it on my systems and even playing around with the code the lines should be visible even if they are "sunken" into the terrain. So I think it is something with the OpenGL driver.
I'll close here.
