### ISSUE TITLE
Windows build testing

### ISSUE THREAD

**Issue by jonaseberle** [qutescoop/qutescoop#15]
When run with Github actions (https://github.com/qutescoop/qutescoop/actions), the Windows build fails during linking:

<pre>
g++ -Wl,-s -Wl,-subsystem,windows -mthreads -o DIST-win32/QuteScoop.exe @object_script.QuteScoop.Release  -lglu32 D:/a/qutescoop/Qt/5.15.1/mingw81_64/lib/libQt5OpenGL.a D:/a/qutescoop/Qt/5.15.1/mingw81_64/lib/libQt5Widgets.a D:/a/qutescoop/Qt/5.15.1/mingw81_64/lib/libQt5Gui.a D:/a/qutescoop/Qt/5.15.1/mingw81_64/lib/libQt5Network.a D:/a/qutescoop/Qt/5.15.1/mingw81_64/lib/libQt5Xml.a D:/a/qutescoop/Qt/5.15.1/mingw81_64/lib/libQt5Core.a temp/win32-release/windowsicon_res.o  -lmingw32 D:/a/qutescoop/Qt/5.15.1/mingw81_64/lib/libqtmain.a -LC:/openssl/lib -LC:/Utils/my_sql/mysql-5.7.25-winx64/lib -LC:/Utils/postgresql/pgsql/lib -lshell32 
temp/win32-release/Tessellator.o:Tessellator.cpp:(.text+0x53): undefined reference to `__imp_glBegin'
temp/win32-release/Tessellator.o:Tessellator.cpp:(.text+0x63): undefined reference to `__imp_glEnd'
...
</pre>
(See https://github.com/jonaseberle/qutescoop/runs/1107121099?check_suite_focus=true)

Help is appreciated.

**Comment by jonaseberle** [comment]
We have the first successful Windows build! :) 

Dear Windows users, please test this and give feedback here:
https://github.com/qutescoop/qutescoop/suites/1384620144/artifacts/22815210

* known issues: METAR download won't work https://github.com/qutescoop/qutescoop/issues/11

**Comment by Luca0208** [comment]
In reference to #18: Stackoverflow says [don't even bother fixing it just link statically](https://stackoverflow.com/a/6405064).

I'm trying that out right now in the [test-workflows branch of my repo](https://github.com/Luca0208/qutescoop/tree/test-workflows) (For test reasons I've removed all the other actions).

**Comment by jonaseberle** [comment]
Great, thank you @Luca0208.

**Comment by jonaseberle** [comment]
I am just linking other cross-platform Qt software with a public build process that I come across:
https://github.com/skiselkov/BetterPushbackC
Just some brain-dump. I haven't looked into it.

**Comment by jonaseberle** [comment]
Btw, does this .zip from @Luca0208 work for Windows users https://github.com/Luca0208/qutescoop/actions/runs/909808772 ?

**Comment by diibify** [comment]
The .zip is `Expired`. Any clue what to do?

**Comment by jonaseberle** [comment]
I've triggered a rebuild in this repository: https://github.com/qutescoop/qutescoop/runs/4422884333?check_suite_focus=true - let's see if it works.

**Comment by diibify** [comment]
Unfortunately it failed and I could not test it.

**Comment by jonaseberle** [comment]
I've played around a bit tonight and I got a successful build with MSVC2019.

Would you Windows users please kindly try downloading this .zip https://github.com/qutescoop/qutescoop/suites/5158223810/artifacts/156034402 ?

For reference: It's coming from this run https://github.com/qutescoop/qutescoop/actions/runs/1786619520
I've got some pretty high hopes for that one ;)

**Comment by diibify** [comment]
The good news: QuteScoop is starting. Thank you very much!
The bad news: The map is not displayed in the whole window (see screenshot). And it looks like it's not loading VATSIM data (even with Daniel's proxy). Anything I can do? 
![QT_Window](https://user-images.githubusercontent.com/16623471/152305112-f228b049-6a80-4a4d-b0f5-9673d9d9982d.jpg)

**Comment by jonaseberle** [comment]
@diibify Thank you for checking!

The proxy is not required any more. These are my settings:
![image](https://user-images.githubusercontent.com/1678001/152310696-d9c8cd25-28bf-4c22-9f02-5c76516c56b8.png)

The funny map positioning is fixable for sure. I can also reproduce the error when I start the Windows version with Wine.

**Comment by diibify** [comment]
Even with the default setting "VATSIM" I could not load any data, so I still tried the proxy. The vatbook data are there.

**Comment by jonaseberle** [comment]
I see something in the log when I start it with with Wine:
`qt.network.ssl: QSslSocket::connectToHostEncrypted: TLS initialization failed` - that points to a missing TLS/SSL openssl lib.

If you see that, too when you start it from the console we have something obvious to chase.

**Comment by diibify** [comment]
No errors in the console so far. There is also no log.txt for this instance in the usual folder
`C:\Users\$user\AppData\Local\QuteScoop\QuteScoop`

**Comment by jonaseberle** [comment]
True. I forgot. I got rid of the [log.txt and in-program log viewer](https://github.com/qutescoop/qutescoop/commit/9fad57bcf17147705da0ca71a5f55e4f79f7e8ff) because I thought it added unnecessary complexity to the code. Maybe that wasn't such a wise idea.

But it should still output all the logging when run from a command line:
![image](https://user-images.githubusercontent.com/1678001/152318032-07afe55c-b888-4967-a9d8-dd22d30a71f7.png)

**Comment by diibify** [comment]
Unfortunately not. Neither with the cmd.exe nor in the PowerShell.
![QT_Console](https://user-images.githubusercontent.com/16623471/152320464-c891817b-08a6-46f2-b60c-72f199b731d6.jpg)

**Comment by jonaseberle** [comment]
I think I have the failed download problem fixed.
I reworked the logging and reintroduced `log.txt`. It behaves the same now on Win and Linux. The problem seemed to have been that the output was `stderr`. Now starting QuteScoop will only output 2 lines (to `stdout`): which settings are used + where it is writing the log file. 

Regarding the layout problem: I fixed it by removing these overlay widgets:
![image](https://user-images.githubusercontent.com/1678001/152382141-886160af-e62a-4540-afee-468156fe70b1.png)
They never worked perfectly for me; all the functions except the wind+cloud data (which stopped working in ~2014 as ) are reachable via the menu.

This https://github.com/qutescoop/qutescoop/suites/5168292614/artifacts/156614129 has all those changes. Thank you for testing :)

**Comment by diibify** [comment]
Many kudos to you! It looks like everything is going as it should. Thank vou very much!

A question of understanding. QT loads the data files from the main QuteScoop folder from /data and no longer from `C:\Users\$User\AppData\Local\QuteScoop\QuteScoop` ?

**Comment by jonaseberle** [comment]
Oh yeah! Thank you for testing. So finally we can care about actually fixing bugs and improving the software.

> A question of understanding. QT loads the data files from the main QuteScoop folder from /data and no longer from `C:\Users\$User\AppData\Local\QuteScoop\QuteScoop` ?

I would like to only use `<directory of QuteScoop.exe>/data` in the future.

Currently, if `<directory of QuteScoop.exe>/(data,downloaded,screenshot,textures)` is writable and if it finds the data there, it will take it.
You can delete `\Users\<user>\AppData\Local\QuteScoop\QuteScoop` if I am not mistaken. It would copy files there if the other location is not writable (I think that is the case when being run from C:\\**Program Files**\\QuteScoop which had/has special protection?). If we are just distributing .zip files from now on we do not care about that, do we?

This is the code: 
https://github.com/qutescoop/qutescoop/blob/5457f61d476b5a80dbeeb1f919f4fe9be8a779de/src/Settings.cpp#L58-L71
what must I have been thinking?! 🤣 That is sooo unnecessarily complicated.

**Comment by jonaseberle** [comment]
Thank you for testing! I made a release https://github.com/qutescoop/qutescoop/releases/tag/v2.3.0.

**Comment by jonaseberle** [comment]
The immediate issues with wrong libraries are solved so I'll close here.

The remaining problem for some Windows users is https://github.com/qutescoop/qutescoop/issues/46.
