### ISSUE TITLE
LSAZ_[E_]CTR not shown on map when online

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#150]
Hi, looks like there is some mapping/outline missing:

![image](https://user-images.githubusercontent.com/63562075/189986926-527d2748-9561-4a60-9073-f6fd0811ec55.png)

but:

![image](https://user-images.githubusercontent.com/63562075/189987002-04bda98b-610b-4dad-9827-8123148191b2.png)

This is using v2.6.3

Best regards,
Daniel

**Comment by jonaseberle** [comment]
I've also realized that yesterday and added them (I just aliased them to the sector of LSAS until we have better data):
https://github.com/qutescoop/qutescoop/commit/da29a32fe571f578d9d91e889d85869666a42a74

The data should be auto-updated for all clients on the next start.
