### ISSUE TITLE
Preparing Textures

### ISSUE THREAD

**Issue by TootY1993** [qutescoop/qutescoop#151]
Hello,

I've been using "QuteScoop-v2.6.3-9-gda29a32-win" for the past 10 hours without issues with multiple restarts.

When now opening the application I'm stuck at 'Preparing Textures' - I have even re-downloaded the application.

Any thoughts on what could be the cause? I have attached the log (if this will help)

Thank you

[log.txt](https://github.com/qutescoop/qutescoop/files/9578160/log.txt)

**Comment by jonaseberle** [comment]
I can't spot an obvious problem.

We just updated `firlist.dat` 2 days ago and see that your client has fetched that already.

"Preparing Textures" point to a problem with the earth textures. Maybe reset that (or delete the whole thing) in Windows registry in \\HKEY_CURRENT_USER\\Software\\QuteScoop\\QuteScoop.

**Comment by jonaseberle** [comment]
@TootY1993 could you solve the problem?

**Comment by TootY1993** [comment]
> @TootY1993 could you solve the problem?

Hello, I do apologise- yes it's all fixed from the advice above.

Thank you.
