### ISSUE TITLE
[Windows 10] Version 2.2 Alpha 1 not starting

### ISSUE THREAD

**Issue by twSimulations** [qutescoop/qutescoop#18]
Content from Zip file (QuteScoop-Win-953fb82c484c77cac9713fd79ea9e9c1eec5ff28.zip) extracted to existing Qutescoop installation folder. Following failures appear when trying to start Qutescoop

![A1](https://user-images.githubusercontent.com/73319881/96943296-f2440400-14d7-11eb-9207-efcb4ded6428.PNG)
![A2](https://user-images.githubusercontent.com/73319881/96943297-f2dc9a80-14d7-11eb-80c4-9bd3022fbfa1.PNG)
![A3](https://user-images.githubusercontent.com/73319881/96943298-f3753100-14d7-11eb-9265-8e91c4ded494.PNG)

**Comment by jonaseberle** [comment]
Hi Tim, thanks for your report.

Could you try with https://github.com/qutescoop/qutescoop/suites/1385865273/artifacts/22852017? That should have at least some of the libraries bundled.

**Comment by diibify** [comment]
After installing the missing .dlls I cant start the app (Windows 10):

![QT2 2](https://user-images.githubusercontent.com/16623471/96996022-72498880-152f-11eb-8eae-a87360bafeba.jpg)

**Comment by twSimulations** [comment]
> Hi Tim, thanks for your report.
> 
> Could you try with https://github.com/qutescoop/qutescoop/suites/1385865273/artifacts/22852017? That should have at least some of the libraries bundled.


This is what I get after overwriting the old files
![A4](https://user-images.githubusercontent.com/73319881/96997233-acb42500-1531-11eb-8d07-c43ae4f60e53.PNG)

**Comment by jonaseberle** [comment]
Guys, report which version you are testing, please! @diibify I am unsure about your version. Are you refering to the one I suggested to @twSimulations?

The download file names all have a unique name.

When in doubt, please open a new ticket.

@twSimulations, ok, so we have gotten one step further. The `Qt*` libraries are there now. We still need the compiler library.
You do not need to overwrite anything. It should be a self-contained .zip file - after unpacking it to a folder it shall be a complete QuteScoop.

You both could help if you would have a look at other Windows builds here https://github.com/qutescoop/qutescoop/actions?query=workflow%3A%22Build+Windows%22 (successful builds will have a downloadable .zip under "artifacts") and see if something is working for you?

I don't have Win 10 (only an old, unupdated 32bit Win 7 in a virtual machine) and can't test it at all.

**Comment by diibify** [comment]
With version https://github.com/qutescoop/qutescoop/actions/runs/323962868 are also some .dlls missing (libgcc_s_seh-1, libstdc++-6, libwinpthread-1). After installing this the error message during loading is still the same as above.

**Comment by twSimulations** [comment]
I still get many error messages. I downloaded the ZIP file from https://github.com/qutescoop/qutescoop/actions/runs/324474143 und extracted the files into a freshly made standalone folder.

![A1](https://user-images.githubusercontent.com/73319881/97044933-29b4be00-1575-11eb-9908-4b2010ceb74d.PNG)
![A2](https://user-images.githubusercontent.com/73319881/97044938-2b7e8180-1575-11eb-9d4b-bfd6e0e03a50.PNG)
![A3](https://user-images.githubusercontent.com/73319881/97044947-2de0db80-1575-11eb-816b-4c4b0851793c.PNG)
![A4](https://user-images.githubusercontent.com/73319881/97044950-2faa9f00-1575-11eb-91f9-c9d1a943a669.PNG)

**Comment by pole95** [comment]
I did some quick testing:

The missing DLL errors can be fixed by statically linking libstdc++ and libgcc to the executable. Running the Github Action with an adapted .pro File to fix this gives the `0xc000007b` when trying to run the artifact.

The `0xc000007b` error seems to indicate that there is an architecture mismatch between the executable and the linked libraries (e.g. 32bit library vs 64bit executable), I am however not competent enough to fix and/or further diagnose that issue in the github runner.

A local compilation using the MSVC toolchain nets me a runnable executable at least (even though there seems to be a problem with the 3D rendering)

**Comment by jonaseberle** [comment]
I guess I am giving up on Windows since it is really far from my interests: I use Linux and am more into the Web Apps side of computing.
I am happy if somebody wants to chime in.

**Comment by jonaseberle** [comment]
Thank you all for your informations. Lets continue to track progress on a Windows build here https://github.com/qutescoop/qutescoop/issues/15
