### ISSUE TITLE
Introduce possiblity to map "arbitrary" controller logins to airports

### ISSUE THREAD

**Issue by jonaseberle** [qutescoop/qutescoop#182]
We have been using workarounds to add controller logins to airports for a long time:

https://github.com/qutescoop/qutescoop/blob/master/src/Controller.cpp#L229-L243

- this "worked" only for 1 airport.

With https://github.com/qutescoop/qutescoop/pull/181 we are using a workaround to at least show the APP circle visually at a "pseudo"-airport.

We finally should introduce a file (suggestion `data/controllerAirportsMapping.dat`) that allows us to properly do this:

* LIMM_APP covers LIMC LIML LIME LSZA
* EDDS_APP also covers EDSB
* Australia uses 2-letter controller logins for many terminal stations https://vatpac.org/controllers/position

The file format could be:
```
; By default airports are assigned to controllers by their common prefix (= ICAO-code). 
; This file allows to add additional airports to a controller
; The fields are:
; 1. Controller Login PREFIX
; 2. Controller Login SUFFIXes (leave empty for any or add multiple space-separated)
; 3. Airports (space-separated)
EDIT: removed the lat/lon: ; 4. + 5. (optional, only used if the PREFIX is not a known airport) latitude + longitude
LIMM:APP:LIMC LIML LIME LSZA
EDDS:APP:EDSB
AD:DEL GND TWR APP DEP:YPAD
```

Then we can undo the workarounds:

- [x] remove LIMM + ESSEX from airports.dat 
- [x] remove https://github.com/qutescoop/qutescoop/blob/master/src/Controller.cpp#L229-L243

**Comment by FlyingFoxVATSIM** [comment]
For terminal control (DEL, GND, TWR, DEP, APP), Australian ATCOs login only with the last two letters of the airport code, e.g. ATCOs at YSSY will login as SY_xxx instead of YSSY_xxx.

Do we want to solve this with a general rule in the code, such as "if country=AU then..." or wait for the new file format?

**Comment by jonaseberle** [comment]
Do they do it for all airports? That seems... kind of wasteful regarding possible logins ;) SY could be YRSY, YLSY, YMSY as well...
Could you make a list?

Unfortunately we can't do it in the simple fashioned way we use for US controllers (if 3 letters then prepend a "K").

I would just add rules for ML_* => YMML and SY_* => YSSY etc. now.
That would be something that we could easily transfer to the new file when I get around implementing it.

**Comment by FlyingFoxVATSIM** [comment]
> Do they do it for all airports? That seems... kind of wasteful regarding possible logins ;) SY could be YRSY, YLSY, YMSY as well... Could you make a list?

They got a list of stations here: https://vatpac.org/controllers/position
If you wish, I can sit down and condense it as to what airport codes are affected.

**Comment by jonaseberle** [comment]
No thanks, that list is great.
