### ISSUE TITLE
Collecting special ATC stations for "controllerAirportsMapping.dat"

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [qutescoop/qutescoop#210]
We got some new or amended stations:

1. ; shortened terminal controllers (USA)
**NY::KLGA KEWR KJFK**

2. ; no-airport-with-that-prefix terminal controller logins
**PCT:APP DEP:KBWI KIAD KDCA KRIC KCHO**

3. ; no-airport-with-that-prefix terminal controller logins
**SCT:APP DEP:KLAX KSAN KPSP KBUR KVNY KLGB**
_Note: list of airports is not exhaustive, do we want to add all of them?_
Source: [LA ARTCC](https://laartcc.org/article/understand-socal-airspace)

**Comment by jonaseberle** [comment]
Thanks!

> SCT:APP DEP:KLAX KSAN KPSP KBUR KVNY KLGB
> Note: list of airports is not exhaustive, do we want to add all of them?
> Source: [LA ARTCC](https://laartcc.org/article/understand-socal-airspace)

If we have a list, let's add them I would say.

**Comment by FlyingFoxVATSIM** [comment]
okay, then it will be:

**SCT:APP DEP:KLAX KSAN KPSP KBUR KVNY KLGB KONT KSNA KSDM KAVX**

**Comment by jonaseberle** [comment]
One more, just discovered
![image](https://user-images.githubusercontent.com/1678001/235463662-5824a161-60f7-4ddf-b2d4-24ca8e97ef3d.png)
```
; controller logins covering additional airports
EDFH:APP DEP:EDDR ETAR
```
---
and many more from clicking around...
![image](https://user-images.githubusercontent.com/1678001/235464084-75b317fa-d96b-4d42-a24e-833764e52ff9.png)
```
; controller logins covering additional airports
LFPG:APP DEP:LFPO LFPB LFPN LFOB
```
---
![image](https://user-images.githubusercontent.com/1678001/235464351-e7a8fdb0-ffe1-4972-81bb-95d1a9b8e8e7.png)
```
; controller logins covering additional airports
EGJJ:APP DEP:EGJA EGJB
```
---
![image](https://user-images.githubusercontent.com/1678001/235464672-72668f9a-306e-4b5b-b5fd-80b233056834.png)
```
; controller logins covering additional airports
ESSA:APP DEP:ESSB
```
---
![image](https://user-images.githubusercontent.com/1678001/235465224-f1cffa6a-196b-40d2-be4c-c387dc01379f.png)
```
; controller logins covering additional airports
RKSS:APP DEP:RKSI
```

**Comment by jonaseberle** [comment]
![image](https://user-images.githubusercontent.com/1678001/235481532-7c81b32f-d11b-46ad-aff9-fc2db7a3d643.png)
```
; controller logins covering additional airports
EDDL:APP DEP:EDLN EDLV
```

**Comment by jonaseberle** [comment]
![image](https://user-images.githubusercontent.com/1678001/235481799-439d2e45-23d0-45a8-a648-bcfa2878d250.png)
```
; controller logins covering additional airports
LPPT:APP DEP:LPCS
```

**Comment by FlyingFoxVATSIM** [comment]
The question is if we want to strictly collect only ATC-stations that do not have a regular airport name, but only special stations, to keep it tidy and easy, e.g. ESSEX_APP covering EGSS EGGW etc.. If it was EGGW_APP (does not exist), it would not be an issue as it would be detected automatically.

**Comment by jonaseberle** [comment]
Yes, we do not have to add the standard case (EGGW_APP => EGGP) and also not the 3 letter US codes (IAD_TWR => KIAD).

**Comment by jonaseberle** [comment]
Sorry, i wrote nonsense or had a typo in there. I meant

> we do not have to add the standard case (EGGW_APP => EGG**W**) and also not the 3 letter US codes (IAD_TWR => KIAD).

I am trying to just make 2 sections in the file: those that have an airport name in their login, and those who don't.
