### ISSUE TITLE
"Display all sectors" not working when re-starting QT

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [qutescoop/qutescoop#23]
In the section "NavData" users can choose "all sectors" to display all sectors that are available. When closing QT and starting it again, the option is still checked active, but the sectors are NOT displayed, users then have to cycle "all sectors" to see them all again.

Is this intentional?

**Comment by jonaseberle** [comment]
That was easy ;) Sorry that you had to wait so long.

A Windows .zip download will be available here https://github.com/qutescoop/qutescoop/actions/runs/1796495197 shortly.
