### ISSUE TITLE
[Improvement] NOT display friend-rings for ATIS stations

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [qutescoop/qutescoop#236]
Now that one ATC can operate ATIS-stations for multiple airports at the same time, it does look a bit crowded when this ATCO is on your friend list - so many friend-rings! Would it be possible to **not** draw those rings for ATIS-stations, but only for actual ATC-stations and pilots?

**Comment by jonaseberle** [comment]
Indeed ;)

![image](https://github.com/qutescoop/qutescoop/assets/1678001/77be2779-6b94-460f-83e0-535b64c8401d)
