### ISSUE TITLE
Make aircraft label content configurable

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#242]
Since recently, aircraft label shows altitude (https://github.com/qutescoop/qutescoop/pull/188). This increases the label significantly and may lead to more clutter in crowded spaces, while altitude might not be too important at all. Thus I suggest to make the altitude info in the aircraft label hidable in preferences. And if you want to go an extra mile, also offer ground speed and potentially other data (like aircraft type) as options what to put into the label.

**Comment by jonaseberle** [comment]
I hear you. What I would especially like is another font for that information and putting it in a second line.
But I don't have that much clutter tbh by limiting the amount of labels to 130.
