### ISSUE TITLE
Qutescoop not downloading controllers' information

### ISSUE THREAD

**Issue by twSimulations** [qutescoop/qutescoop#26]
'Controller info' and ATIS boxes are blank and empty.

![162](https://user-images.githubusercontent.com/73319881/101827992-457a2080-3b31-11eb-91ce-36db91944d7f.PNG)
![160](https://user-images.githubusercontent.com/73319881/101827988-4448f380-3b31-11eb-9fd1-68dd4debc460.PNG)
![161](https://user-images.githubusercontent.com/73319881/101827991-44e18a00-3b31-11eb-886d-6d6acf5e01ef.PNG)

**Comment by droesen** [comment]
Are you sure the controller info data was actually in VATSIM's data feed? You can make QuteScoop save the downloaded data files in its AppData folder to verify.

**Comment by jonaseberle** [comment]
We have the controller info back since the switch to the new VATSIM format #25 

<img width="368" alt="image" src="https://user-images.githubusercontent.com/1678001/117890325-41575800-b2b5-11eb-9beb-f36962d78bac.png">

I am unsure about the ATIS. Maybe @Luca0208 knows something.

**Comment by Luca0208** [comment]
Actually it turns out ATIS and controllers are split in the new datafeed, totally missed that, sorry.
I'll make a fix shortly.
