### ISSUE TITLE
Route not resolved completely

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#27]
Recently flown KJFK-KMCO, using routing:

![image](https://user-images.githubusercontent.com/63562075/103180612-83987380-4897-11eb-92b6-b97132b33cc3.png)

The part "WAVEY EMJAY J174 ORF" is correctly resolved, but "J121 CHS" is missing completely, as well as "Q85 LPERD". Other tools like SimBrief, SkyVector etc. have no problems resolving the routing completely, including the ToLiSS A319 FMS on X-Plane 11.50. Didn't check the X-Plane 10.30+ airway data used (here) solely by QuteScoop though, so problem might lie in the navdata (cycle 2013).

It's not the first route I didn't see fully resolving, so I guess it's a systemic problem either in QS or the navdata...

**Comment by droesen** [comment]
Full WP list would be:

WAVEY EMJAY YAZUU ZIZZI WARNN SWL DUNFE KALDA SAWED ORF WEAVR ISO BARTL JMACK CHS IGARY ROYCO GIPPL BEEGE LPERD OMN

as per SkyVector: https://skyvector.com/api/navlog?40776

**Comment by jonaseberle** [comment]
I've just checked with Navigraph's X-Plane 10 (yes, we should upgrade...) data AIRAC 2201.

And yes...
```
KJFK
SKORR4.YNKEE WAVEY EMJAY J174 ORF J121 CHS IGARY Q85 LPERD OMN CWRLD4
KMCO
```
still resolves to
`KJFK WAVEY EMJAY YAZUU ZIZZI WARNN SWL DUNFE KALDA SAWED ORF IGARY OMN KMCO`
in QuteScoop.

**Comment by jonaseberle** [comment]
Just an idea:

It would be nice if we would show route resolving problems whenever we show the resolved waypoints.
For example in the pilot detail dialog or here:

![image](https://user-images.githubusercontent.com/1678001/152987248-4fed6a59-ce02-444d-92d6-cd98a9640351.png)

It would be helpful to be able to show something like 
`YNKEE WAVEY EMJAY YAZUU ZIZZI WARNN SWL DUNFE KALDA SAWED ORF (no link to CHS via J121) IGARY (no link to LPERD via Q85) OMN` (just an example, I did not really check).

If we have problems with reading/using the AIRAC that would encourage users to file bug reports. 
And if we fixed those problems, it would have some nice value for users.

**Comment by droesen** [comment]
Another case of not properly resolved routing in v2.6.3 with navigraph navdata:

Filed route: ALG Y109 UMTEX Y100 TRA Z69 OLBEN/N0470F310 N869 NEMOS DCT GVA DCT INCUS DCT BALSI UN852 DIVKO UN975 BCN UM985 VIBAS/N0469F330 UM985 MGA UN851 VJF UL82 IBALU UN857 TERTO

resolved: ALG ROREM UMTEX TRA OLBEN LUTIX BENOT NEMOS GVA INCUS BALSI KOTIT RETNO DOTIG GIROL TUPOX MTG DIVKO MGA BRIKE VJF TAVSI RUNAX IBALU ERMED TOVRA VEDOD TERTO

There are a lot of points missing between DIVKO [UN975 BCN UM985] MGA

should be: ... DIVKO NILDU BISBA BGR NENDA BCN RODRA PEXOT EBROX LOTOS TORDU DIKUT SOPET VLC SERRA ASTRO POBOS XEBAR YES MAMIS BAZAS VIBAS MGA ...

**Comment by jonaseberle** [comment]
I took a part of that route to create a [minimal reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example):

```
LFML
DIVKO UN975 BCN
LEBL
```
(AIRAC 2210)

QuteScoop resolves it to `DIVKO`.
Should be `DIVKO NILDU BISBA BGR NENDA BCN`.

**Comment by jonaseberle** [comment]
Ok, I think I have found and squashed all the bugs :) Some have been there forever so thank you for reporting it!
