### ISSUE TITLE
Wrong interpretation of Lat/Lon waypoint

### ISSUE THREAD

**Issue by ogruetzmann** [qutescoop/qutescoop#320]
Flying from SBRF to FHAW I had 0730S03045W in my flight plan. Instead of 0730S, it was plotted to 0730N on the map.
https://i.imgur.com/cNflWxe.png
https://i.imgur.com/Ta2ltEV.png

**Comment by jonaseberle** [comment]
Which version please? This probably has been fixed.

**Comment by ogruetzmann** [comment]
2.10

**Comment by jonaseberle** [comment]
Hi Oliver, yes that has been fixed. We haven't had a public release for a long time although there have been many fixes and changes (shame on me). But we are testing and very close to a new release now I would say.

Also reported in https://github.com/qutescoop/qutescoop/issues/264.

I think it was finally fixed [here](https://github.com/qutescoop/qutescoop/commit/1ba48755225542ddce5118196f6d76d7511c08c2#diff-90d019f32e62565b02f891d32196587f95f8e71d5cf44df4c2383e3ca8fd77b2R298-R300).
