### ISSUE TITLE
Crash upon opening

### ISSUE THREAD

**Issue by SilageKingHumble101** [qutescoop/qutescoop#326]
Hello Everyone 

Sorry if this is the wrong place, but I couldnt find any other Support Forum. I was very excited to get my favorite vatsim Viewer back on my PC. I have Version 2.10 of Qutescoop and am on Windows 10 Build 19045.3086. I deleted the Folder with the old version of Qutescoop and using Control Panel Programs I dont see any Qutescoop versions registered (if I remember correctly though it was always "folder based"). 
When I try to open QuteScoop.exe the application opens briefly (main window, Friends box and Search Box) before closing after about 1s. This doesn't change when trying Run as administrator. 
Am I the only one with this issue? How can I trouble shoot it?
Thanks for the Help!

Cheers

**Comment by jonaseberle** [comment]
Hi, this is the right place.
Earlier we had installers, now it is just a folder (no installation).

To have any idea what's going on we would need the `log.txt` that gets written in the main folder.
Maybe you have some incompatible settings in the registry. You can delete everything you find by the name "QuteScoop" with regedit.exe.

**Comment by SilageKingHumble101** [comment]
Hey Jonas 

Thanks for reaching out. I went through the regedit and removed everything I could, I did get a few error messages on some files/keys. 
When I redownloaded and tried to start Qutescoop it now loads from the "classic" first map position, but still closes after 1s. I have attached my log file. Hope this provides some insight. 

Cheers

Pascal
[log.txt](https://github.com/qutescoop/qutescoop/files/11972238/log.txt)

**Comment by jonaseberle** [comment]
Hey Pascal,

I don't see anything interesting. It crashes after it received the network status, but before actually rendering it.
You can try the release candidate for v3 https://github.com/qutescoop/qutescoop/releases

**Comment by SilageKingHumble101** [comment]
> Hey Pascal,
> 
> I don't see anything interesting. It crashes after it received the network status, but before actually rendering it. You can try the release candidate for v3 https://github.com/qutescoop/qutescoop/releases

Hey Jonas 

Thanks! rc3 for v3 is staying open. No idea, probably some old file somewhere I missed. Thanks alot for the help, I'm very excited to get back into Qutescoop :)

Cheers

Pascal
