### ISSUE TITLE
[IMPROVEMENT] ATIS letter recognition

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [qutescoop/qutescoop#328]
Hi Jonas,

I just saw that the ATIS letters of some airports/ATIS-stations were not recognized by Qutescoop. See screenshot.
![sceenshot_07112023_104412](https://github.com/qutescoop/qutescoop/assets/66524946/8f3f566c-c535-43bc-963e-ecce177da4f0)

**Comment by jonaseberle** [comment]
Yes, that happens. Controller/ATIS clients don't always transmit it to the network so it is not always included in the data feed.

**Comment by FlyingFoxVATSIM** [comment]
From what I understand all those stations had a readable ATIS, but Qutescoop did not recognize the letters? The same ATCO also had an ATIS for VVTS (I think) that had "INFORMATION ALPHA" and QS displayed it correctly.

**Comment by jonaseberle** [comment]
I always thought that might be because the used client does not transmit it at all.

That might be right sometimes, but checking [the stream](https://data.vatsim.net/v3/vatsim-data.json) repeatedly shows that the `atis_code` is sometimes there, sometimes not and the state changes for the same station... 

Weird, would need fixing on VATSIM side. 
I guess the feed generator receives that status package from the client but resets its state when it does not see that package for some time. Seems to happen more often for Asian stations?

**Comment by FlyingFoxVATSIM** [comment]
I will check the datafeed next time I observe this kind of situation!

**Comment by jonaseberle** [comment]
It seems the problem is not present currently.

Just a note for me how to check that:
```
watch "curl --silent https://data.vatsim.net/v3/vatsim-data.json | jq -r '.atis[] | select(.atis_code==null).callsign'"
# or
watch "curl --silent https://data.vatsim.net/v3/vatsim-data.json | jq -c '[.atis[] | [.callsign,.atis_code]]'"
or
watch "$(cat <<'EOL'
data="$(curl --silent https://data.vatsim.net/v3/vatsim-data.json)"; update_timestamp="$(jq '.general.update_timestamp | strptime("%Y-%m-%dT%H:%M:%S.%GZ") | mktime' <<<"$data")"; echo "updated $update_timestamp"; jq -r ".atis[] | select(.atis_code==null) | {callsign:.callsign, text_atis0: .text_atis[0], onlineSince_sec:($update_timestamp - (.logon_time | strptime(\"%Y-%m-%dT%H:%M:%S.%GZ\") | mktime))}" <<<"$data"
EOL
)"
```
I only see ATISes that have been online less than 3 min (EDIT: or do not have ATIS text either) without ATIS letters.

**Comment by jonaseberle** [comment]
It seems the VATSIM stream has improved, probably by setting a higher interval in which it expects to receive the ATIS letter from controller clients. 

I think we can close here.

Ref: https://github.com/orgs/vatsimnetwork/discussions/7
