### ISSUE TITLE
EKVG airport now also covered by BIRD_CTR

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [qutescoop/qutescoop#336]
A user just reported that BIRD_CTR covers EKVG airport during the absence of local ATC. Is there anything we can do in Qutescoop to reflect this?

vatglasses.uk does show this dependency, but I guess we are not in the position of showing this, are we?

**Comment by jonaseberle** [comment]
Hi Fox,
since the BIRD and BIRD_E sectors laterally cover EKVG already, we show an online _CTR as active ATC for the airport already.

So I think that's fine from our side.

**Comment by FlyingFoxVATSIM** [comment]
Ok thanks, apparently it did not show this for the user. I need to ask him.

**Comment by jonaseberle** [comment]
I added test data so we can test by setting "user defined network": `https://raw.githubusercontent.com/qutescoop/qutescoop/master/tests/fixtures/issue-336/status.json` to simulate BIRD_CTR and BIRD_E_CTR online.

It looks ok to me (with the latest dev version at least):
![image](https://github.com/qutescoop/qutescoop/assets/1678001/16be57ff-2f20-4668-8acf-e3cbada5ea1b)

**Comment by jonaseberle** [comment]
Currently with live coverage:

![grafik](https://github.com/qutescoop/qutescoop/assets/1678001/c659e0f9-5442-475e-a799-aa6801a47f13)

– so I guess we are fine.
