### ISSUE TITLE
Remove rating from default secondary label

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#337]
Given that actual performance is only very roughly related to rating, we shouldn't display it so prominently in default labels.
This declutters labels as well.

Food for thought.

**Comment by jonaseberle** [comment]
Anybody can just remove it. 

For me it is interesting. I put it in the default label settings because (although I never found the courage to do it, shame on me) I like to promote the idea of PTD courses to further knowledge.

**Comment by jonaseberle** [comment]
I'll close here.
