### ISSUE TITLE
Replace SOBT with EOBT labeling

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#338]
This is related to v3.0.0-rc3:

ATC details dialog shows "SOBT" for not yet departed aircraft. This is technically wrong as the information is derrived from the FPL, so that's actually EOBT, not SOBT.

**Comment by jonaseberle** [comment]
We discussed it and decided that "scheduled" is currently the best naming for it. I think it makes sense in the QuteScoop context - everything FP is now "scheduled" and calculated ("live") values are "estimated".

Sorry, I am not going to change it back.

Related: https://github.com/orgs/vatsimnetwork/discussions/20
A bit related (the flightplan form in general): https://github.com/orgs/vatsimnetwork/discussions/21

**Comment by droesen** [comment]
This is sad, as calling the EOBT "SOBT" is just plain wrong and teaching pilots just another wrong terminology.
EOBT is not "live"/"calculated", it's the planned off-block time as communicated via the flight plan. SOBT is the assigned airport slot from slot coordinator to the airline. We have no SOBT whatsoever in VATSIM. What comes closest would be the assigned departure slots in "slotted events" where pilots book a certain departure time. THIS is what we could call SOBT. The pilot is then required to file a FPL with EOBT = SOBT.

See https://www.prg.aero/en/explanation-abbreviations-cdm for a run-down.

Please re-consider.
