### ISSUE TITLE
Missing facility type column label in airport details

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#339]
The airport details dialog controller list is missing the label for the controller facility type:

![image](https://github.com/qutescoop/qutescoop/assets/63562075/49224833-8df4-4c2c-8bdb-2354e3bd85ab)

Version: v3.0.0-rc3

**Comment by jonaseberle** [comment]
I don't think it is important to have a column header there. Chances are I removed it consciously but I can't remember now honestly.
