### ISSUE TITLE
Black background on some airport details labels

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#340]
This is with v3.0.0-rc3:

![image](https://github.com/qutescoop/qutescoop/assets/63562075/3c71ca8c-8cc8-4725-bdce-1effd7f1f5cb) ![image](https://github.com/qutescoop/qutescoop/assets/63562075/b9fdc6e5-04d6-4b5f-bef5-731bc885b057) ![image](https://github.com/qutescoop/qutescoop/assets/63562075/feb02434-8e63-4d65-9a1b-8912468d40e3)

This seems to be some kind of highlighting, but in the current form probably unintentional?!

In case Preferences->Display->"bright label text "backdrop color setting shoudl apply here - it doesn't for me.

Maybe we can display passed EOBT (not SOBT, see other issue) and low TTG in red text color?
I personally see no point in highlighting the ATC facility column, but that's just me. :-)

**Comment by jonaseberle** [comment]
The "backdrop" only refers to the labels on the map.

Yes, it is some kind of highlighting ;) For planes these are the "filtered" movements and the column is the one that's most influential for that.

Those are also not colours that I chose - they are part of the operating system/desktop environment colour palette and we just swap them for inverted text.
This is how it looks like in dark mode for example:
![image](https://github.com/qutescoop/qutescoop/assets/1678001/858f14a3-c8a1-4e2a-9a4c-7c3ad98f3a91)

I generally don't like special colors (that are not part of a theme palette), and will especially not hard wire any green/yellow/red into the program. I know users that like to use these colours, though :)

We have 
* bold (used for friends), italic (prefiled flights)
* normal/light (as used in the pilot detail dialog)/inverted colour
* default user's text font / default monospace font
as options to convey meaning. The dialogs should look like the operating system IMHO. The map is a different domain, though.

**Comment by jonaseberle** [comment]
I'll close here.
