### ISSUE TITLE
Broken ATC bookings with v3.0.0-rc.3

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#343]
Config:

![image](https://github.com/qutescoop/qutescoop/assets/63562075/00ad5c13-7d61-41c5-9662-b761a28886a3)

Can't see any booking for today:

![image](https://github.com/qutescoop/qutescoop/assets/63562075/72aaf0c2-8ef3-4ef9-910f-2ad7f22ddf94)

Related to "Bookings never updated"? But why? Checking http://vatbook.euroutepro.com/servinfo.asp via web browser works for me, and contains bookings for today.

BTW, should we use new VATSIM bookings API already?

**Comment by droesen** [comment]
Partly user error... IMHO current QuteScoop should automatically replace the old VATBook URL with the new VATSIM API URL https://atc-bookings.vatsim.net/api/booking when detecting the old one.

**Comment by droesen** [comment]
For whatever reason, HKEY_CURRENT_USER\SOFTWARE\QuteScoop\QuteScoop\settings\version is 7 here (whyever...) - and thus the automatic change of URL by QuteScoop probably didn't happen.

**Comment by jonaseberle** [comment]
I checked the code and I can't reproduce a situation where the migration would NOT run.
But maybe I am overlooking something.
