### ISSUE TITLE
New EuroCenter VACC sectors

### ISSUE THREAD

**Issue by jonaseberle** [qutescoop/qutescoop#357]
https://euc-vacc.net/sectors

**Comment by FlyingFoxVATSIM** [comment]
Done, at last :)
[SectorUpdate_26OCT2023.zip](https://github.com/qutescoop/qutescoop/files/13180385/SectorUpdate_26OCT2023.zip)

**Comment by jonaseberle** [comment]
Thanks! :)

![grafik](https://github.com/qutescoop/qutescoop/assets/1678001/ecceea07-bf51-41d1-858c-7747c24b68c6)
