### ISSUE TITLE
Window closes after loading

### ISSUE THREAD

**Issue by SilageKingHumble101** [qutescoop/qutescoop#369]
Hey Everyone 

I just reinstalled my system and am trying to get Qutescoop running again on Windows 11. When I open Qutescoop (as admin and also just with a double click) I see the loading splashscreen, it briefly opens Qutescoop but then closes the entire application down. 
I've attached the log file. I fear I've installed something wrong but I'm stuck on my journey to a solution. Hoping you can help me :) 

Cheers

SKH
[log.txt](https://github.com/qutescoop/qutescoop/files/13615501/log.txt)

**Comment by SilageKingHumble101** [comment]
I just remembered I had this issue a few months ago. Found my old Github Thread, installing the release candidate for v3 has worked again now. Closing this issue. Sorry for the hastle.

**Comment by jonaseberle** [comment]
Sorry, from your log I have no idea. Something during initialization of the OpenGL graphics context.

You could try the 3.0 release candidates https://github.com/qutescoop/qutescoop/releases
