### ISSUE TITLE
QS immendiatel

### ISSUE THREAD

**Issue by GVA1055** [qutescoop/qutescoop#381]
Hello
I use Qutescoop for VATSIM and have been very satisfied so far.
However, since the last DE update of Windows 11, QS starts and then immediately shuts down again.
I have now tried several options, whether as ADMIN or without, in safe mode or as admin with full rights... QS crashes immediately.

I have the following errors in the event display:
Name of the faulty application: QuteScoop.exe, version: 0.0.0.0, timestamp: 0x645d6abc
Name of the faulty module: QuteScoop.exe, version: 0.0.0.0, timestamp: 0x645d6abc
Exception code: 0xc000041d
Fehleroffset: 0x000000000002ff58
ID of the faulty process: 0x0x82D8
Start time of the faulty application: 0x0x1DA4EB512F84A33
Path of the faulty application: D:\Temp\QuteScoop-v2.10.0-win(4)\QuteScoop.exe
Path of the faulty module: D:\Temp\QuteScoop-v2.10.0-win(4)\QuteScoop.exe
Berichtskennung: b574e60f-842c-401f-8658-f5a8c6cb0dfb
Full name of the corrupted package: 
Application ID that is relative to the faulty package: 

(no further entry here)

Translated with DeepL.com (free version)

**Comment by jonaseberle** [comment]
Please add your log.txt https://github.com/qutescoop/qutescoop/wiki/Help-%5Bold%5D#logtxt

**Comment by GVA1055** [comment]
Thx, I have copy the log file

**Comment by jonaseberle** [comment]
I do not see it.

**Comment by GVA1055** [comment]
[log.txt](https://github.com/qutescoop/qutescoop/files/14039149/log.txt)

**Comment by GVA1055** [comment]
I have dowload the latest v3.0.0-rc3-31 and these Version are running :-)

**Comment by jonaseberle** [comment]
Oh, you added your log.txt to our Wiki as a footer. I am removing that again.

Unfortunately I don't see the reason for your crash with v2.10 in your log.

**Comment by GVA1055** [comment]
HHHMMM. After I´m close the Beta Version and starte teh V2 it runs´2-3 mins and than ... he ist closing again.

But at the Log File, there are no other line´s ....

**Comment by jonaseberle** [comment]
Sorry, without any more information we are not able to help here.
