### ISSUE TITLE
Certain Facilities are not shown on Qutescoop

### ISSUE THREAD

**Issue by SpectreLoki** [qutescoop/qutescoop#389]
Good Day,

I'm not sure if this is an actual error of Qutescoop or if it's a configuration issue somewhere else but for us in HCF certain positions are not being displayed on the map or the detail window for an airport. 

Like here for Maui (PHOG), Approach and also the positions under approach like  Tower and Ground are not shown in the ATC list when active.
![image_2024-03-22_111233283](https://github.com/qutescoop/qutescoop/assets/98547490/af0002d5-523e-49b4-a99e-5975190a5b6a)

Same applies for Honolulu where only Center is actually shown as active in the ATC list and everything under it isn't shown at all. ATIS on the other hand is always shown properly. And when you look into the "Clients and servers" list the positions are shown properly online there. 

![image_2024-03-22_111432383](https://github.com/qutescoop/qutescoop/assets/98547490/85f69916-5cf2-4fcc-862d-60f3663775c1)

On the Data Admin side of things they are properly setup with coordinates etc. so not sure where that issue is coming from.

**Comment by jonaseberle** [comment]
Hi SpectreLoki,
I think the non-standard mapping of that station is not in our data yet.
We can add it here:
https://github.com/qutescoop/qutescoop/blob/master/data/controllerAirportsMapping.dat
Do you have a list of stations and what airports they serve for your vACC?

**Comment by SpectreLoki** [comment]
Hi Jonas,

I will prep it for you and have it handy either later today or tomorrow

**Comment by SpectreLoki** [comment]
I actually also see in the file you linked why it's not working, HCF and Guam CERAP are having the P prefix for airports and not the K like other US airports, so it's PHNL for example. 

HNL::PHNL
HNL:APP:PHNL PHJR PHHI
ITO::PHTO
OGG::PHOG
NGF::PHNG
BKH::PHBK
BSF::PHSF
HHI::PHHI
JRF::PHJR
KOA::PHKO
LIH::PHLI
MKK::PHMK

GUM::PGUM
GUM:APP:PGUM PGUA
UAM::PGUA
GSN::PGSN

These are all the airports that are staffed by us, all other airports are considered uncontrolled

**Comment by SpectreLoki** [comment]
I'm the FE there btw ;)

**Comment by jonaseberle** [comment]
Thanks @SpectreLoki for your contribution!

QuteScoop will auto-update the data files on the next start.
