### ISSUE TITLE
Add Chinese Airports

### ISSUE THREAD

**Issue by twSimulations** [qutescoop/qutescoop#391]
ZGBH:Beihai Fucheng:Beihai:CN:21.53900:109.29400
ZGHZ:Huizhou Pingtan:Huizhou:CN:23.04800:114.60000
ZGOW:Jieyang Chaoshan Intl:Chaoshan:CN:23.55200:116.50600
ZGZH:Liuzhou Bailian:Liuzhou:CN:24.20700:109.39100
ZHEC:Echeng:Ezhou:CN:22.30900:113.91600
ZHNY:Nanyang Jiangying:Nanyang:CN:32.98100:112.61500
ZHYC:Yichang Sanxia:Yichang:CN:30.55600:111.48000
ZPBS:Baoshan Yunrui:Baoshan:CN:25.05300:99.16800
ZPMS:Dehong Mangshi Intl:Mangshi:CN:24.40100:98.53200
ZSCG:Changzhou Benniu Intl:Changzhou:CN:31.90200:119.78100
ZSLG:Lianyungang Huaguoshan:Lianyungang:CN:34.57200:118.87400
ZSLQ:Taizhou Luqiao:Luqiao:CN:28.56200:121.42900
ZSLY:Linyi Qiyang Intl:Linyi:CN:35.04900:118.41200
ZSNT:Nantong Xingdong Intl:Nantong:CN:32.07100:120.97600
ZSQZ:Quanzhou Jinjiang Intl:Quanzhou:CN:24.79900:118.58900
ZSWX:Sunan Shuofang Intl:Wuxi:CN:31.49300:120.42800
ZSXZ:Xuzhou Guanyin Intl:Xuzhou:CN:34.05900:117.55500
ZSYA:Yangzhou Taizhou Int:Yangzhou:CN:32.56200:119.71500
ZSYN:Yancheng Nanyang Intl:Yancheng:CN:33.42600:120.20300
ZSYW:Yiwu:Yiwu:CN:29.34500:120.03200
ZSZS:Zhoushan Putuoshan:Zhoushan:CN:29.93400:122.36200
ZULZ:Luzhou Yunlong:Luzhou:CN:28.85300:105.39100
ZUMT:Zunyi Maotai:Maotai:CN:27.81600:106.33300
ZUYI:Xingyi Wanfenglin:Xingyi:CN:25.08800:104.95900
ZUZY:Zunyi Xinzhou:Zunyi:CN:27.80200:107.24900

**Comment by jonaseberle** [comment]
Thank you!

**Comment by twSimulations** [comment]
@jonaseberle I just realised that one airport coordination had been set wrong

ZHEC:Echeng:Ezhou:CN:30.34300:115.03000
