### ISSUE TITLE
Misrata ICAO ID change HL76->HLMS

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#395]
Hi,

Misrata airport is in airports.dat as HL76, but official code is (since at least 2012) HLMS.

Ref official AIP: https://caa.gov.ly/ais/ad/
specifically https://caa.gov.ly/ais/wp-content/uploads/2017/AIP/AD/HLMS.pdf

Suggest to add an alias (if technically possible) to allow the old ID HL76 too.

Best regards,
Daniel

**Comment by jonaseberle** [comment]
Thank you and sorry for the late reaction!
Fixed in https://github.com/qutescoop/qutescoop/pull/398
