### ISSUE TITLE
Missing sectors

### ISSUE THREAD

**Issue by diibify** [qutescoop/qutescoop#4]
LFUP_CTR
VABB_CTR
ML-ASP_CTR
RU-SC_FSS
ADR_CTR
LTC_CTR
EIDW_I_CTR
ML-ESP_CTR

**Comment by jonaseberle** [comment]
I am sorry, we are going to reimport code from sourceforge before we can start here.
Unfortunately I'll have to delete and recreate the project. I'll do that by this weekend.
