### ISSUE TITLE
Labels on map not clickable // Nvidia QGLWidget mouse coordinates

### ISSUE THREAD

**Issue by twSimulations** [qutescoop/qutescoop#46]
I am used to have quick access on detailed information about a flight or an airport when I click on the callsign or four-letter code. But this doesn't work on the latest release of Qutescoop

**Comment by jonaseberle** [comment]
Hi @twSimulations, thank you for testing.

Do you maybe have "simple labels" active?
![image](https://user-images.githubusercontent.com/1678001/152473392-2427329a-b3e3-4ace-87d1-621bc9c756a7.png)
While being a lot faster on some machines, it comes with the downside of pretty small click spots.

**Comment by dsamuelis** [comment]
Thank you for reviving Qutescoop💜 
+1 for me on that issue, clicking on airport/aircraft labels does not do anything. Having simple labels activated or deactivated has no effect. Also right click on the label, which was previously toggeling route draw, does not work.

EDIT: log attached
EDIT2: Windows ist ein Windows 11 bei mir, weiss nicht ob das irgendwelche Auswirkungen hat...
[log.txt](https://github.com/qutescoop/qutescoop/files/8003755/log.txt)

**Comment by diibify** [comment]
There are absolutely no problems with me. Right-click on aircraft shows routes, right-click on airports shows all incoming and outgoing routes. Left-clicking on aircraft and airports works.
[log.txt](https://github.com/qutescoop/qutescoop/files/8003456/log.txt)

**Comment by twSimulations** [comment]
Solution found:
You must grant admin-access-rights to Qutescoop

**Comment by jonaseberle** [comment]
> Solution found: You must grant admin-access-rights to Qutescoop

Ooooooh. I would not see that as a proper fix and would rather keep the issue open. It is also not just about you: we need to understand the workarounds well so that we can give proper advise to other users ;)

Could you please also attach a log.txt with/without Admin mode enabled? Please also give feedback if you had "simple labels" enabled or not. 
Thanks! 

For reference and for those interested:
The code part in question is:
https://github.com/qutescoop/qutescoop/blob/master/src/GLWidget.cpp#L1475-L1520

The important `_fontRectangles` get compiled in ...
https://github.com/qutescoop/qutescoop/blob/master/src/GLWidget.cpp#L1234

... which uses the "simple labels" switch here ...
https://github.com/qutescoop/qutescoop/blob/master/src/GLWidget.cpp#L1348-L1354

**Comment by jonaseberle** [comment]
@dsamuelis Thank you for the log.txt. I don't spot anything. That's unfortunate :(

Let's just note for now:

## clicking pilot/controller/airport labels

Right clicking on labels draws a pilot's/airport's route(s).
Left clicking should show the info window.

| OS | GPU | driver | simple labels | works? | user
|---|---|---|---|---|---|
| Win11 | NVIDIA GeForce RTX 2060 |  | yes | no | @dsamuelis 
| Win11 | NVIDIA GeForce RTX 2060 |  | no | no | @dsamuelis

**Comment by dsamuelis** [comment]
I can exclude Win11 being the reason, Qutescoop works as intended on my Win11 laptop. Left and right clicks on labels give detail information and toggle route draw.
[log.txt](https://github.com/qutescoop/qutescoop/files/8007541/log.txt)

I will collect some more info on my main FS PC where it is not working in the afternoon (gpu driver version etc). One thing that could cause issues is that I'm using a multi monitor setup on that PC.

GPU driver: Nvidia Game Ready 496.49. After update to 511.65 unchanged behavior

**Comment by dsamuelis** [comment]
One observation: clicking on the labels works for me for the first time starting Qutescoop after a system reboot.
Starting Qutescoop the second and subsequent time, clicking on labels has no effect, as described above.

2 logs attached of a Qutescope start right after reboot (log_working) and a subsequent start where the labels do not work.
[log_working.txt](https://github.com/qutescoop/qutescoop/files/8007849/log_working.txt)
[log.txt](https://github.com/qutescoop/qutescoop/files/8007851/log.txt)

**Comment by dsamuelis** [comment]
And just to confirm: starting Qutescoop as admin, it also works fine for me
[log.txt](https://github.com/qutescoop/qutescoop/files/8007886/log.txt)
.

**Comment by jonaseberle** [comment]
Thank you @dsamuelis for that information.

I guess that points towards an issue with the Nvidia driver and OpenGL that somehow disappears when being run as admin.

I have added your findings to the [Wiki](https://github.com/qutescoop/qutescoop/wiki/OpenGL-issues). It would be great if others could add theirs there as well.

I am pretty much in the dark what causes the problem.

**Comment by dsamuelis** [comment]
I've been investigating this issue a bit more: 
**The labels are actually working for me, but there is a vertical offset between clickspot and label, that is bigger than the label itself. That's why it looked like clicking was not working.** 

If I click ~50px above the label, info box and route draw work as intended. Please see the video here, where whenever the cursor rests, I'm clicking the mouse: https://1drv.ms/u/s!AmZkEbQ856z9hMlp22rPx4sRD7CKew?e=j3t7hH

Running as admin, the offset is gone and everything works as intended.

**Comment by jonaseberle** [comment]
@dsamuelis That are some interesting findings.
Is it always the same distance and always above? Also on the Southern Hemisphere?

**Comment by dsamuelis** [comment]
@jonaseberle now I cannot reproduce the issue anymore. Clicking the labels works fine every single time now.

What have I done in the meantime? I've played SimAirport... maybe this has reset somehing in my OpenGl...
But even after reboot, it works fine for me now. 

I attach a log of the now working Qutescoop, maybe you can spot a difference.
[log.txt](https://github.com/qutescoop/qutescoop/files/8009895/log.txt)

**Comment by dsamuelis** [comment]
@jonaseberle OK even crazier, now I have run Chrome, and the issue is back...!

Yes the offset is always the same (ca 1.5 mouse cursor width on top of the label), also on the southern hemisphere. It is also independent of latitude.

**Comment by dsamuelis** [comment]
@jonaseberle Indeed I can systematiccally reproduce the issue: 

If I run SimAirport, close it and then start Qutescoope: no offset 
[log_withoutoffset.txt](https://github.com/qutescoop/qutescoop/files/8009913/log_withoutoffset.txt)

If I run Chrome, close it and then start Qutescoop: vertical offset 
[log_withoffset.txt](https://github.com/qutescoop/qutescoop/files/8009914/log_withoffset.txt)

**Comment by jonaseberle** [comment]
Hm. It might still be that we are doing something wrong or could do something better. Even though it is also driver related. It is also a very real possibility that we won't see it any more in another driver version.

Since we also have some hardware-dependant performance problems, it is worth chasing this.

I can't promise currently when, but I think about doing different builds where we just alter the GL initialisation slightly each time. Just some "explorative" (that's the word when developers have no clue) testing.

**Comment by droesen** [comment]
> **The labels are actually working for me, but there is a vertical offset between clickspot and label, that is bigger than the label itself. That's why it looked like clicking was not working.**

Same observation here. It's not always happening, and restarting QuteScoop doesn't generally fix it.

Here is an example for the displaced clickspot:

![image](https://user-images.githubusercontent.com/63562075/152701544-1f88bf2a-f2cb-4134-b508-50839a146f59.png)

This is on Win10 / NVIDIA. The older QuteScoop didn't exhibit this problem, ever.

**Comment by droesen** [comment]
And just that I wrote it, restarting QuteScoop fixed it this time.

**Comment by jonaseberle** [comment]
@droesen Thanks for reporting. Could you add yourself to the [Wiki](https://github.com/qutescoop/qutescoop/wiki/OpenGL-issues)? The `GL_RENDERER` / `GL_VERSION` are in the `log.txt`.

**Comment by droesen** [comment]
> @droesen Thanks for reporting. Could you add yourself to the [Wiki](https://github.com/qutescoop/qutescoop/wiki/OpenGL-issues)?

Need to find out how. :-) Also: what is "run as Admin" supposed to mean? There are different shades of that... my user has admin rights, but I'm not executing qutescoop.exe explicitly via "run as administator". This is technically a difference! So what is mean with that column?

**Comment by droesen** [comment]
Looks like you have to add me as a developer to the project... I neither have "edit" nor "new" page options on the Wiki available to me.

Anyway, here's the data:
- v2.3.0 / Win 10 21H1 / NVIDIA
- GL_RENDERER: NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
- GL_VERSION:  4.6.0 NVIDIA 497.09
- not using "simple labels"
- not using "run as admin", but user has admin rights
- works "sometimes"

**Comment by jonaseberle** [comment]
@droesen thanks!
The wiki was restricted to "Users with push rights". That was not intended. Could you check if it is working now?

**Comment by jonaseberle** [comment]
I just had an idea regarding the "~50px above"...
Does that change if the "Time Warp" (F8) panel is shown?
![image](https://user-images.githubusercontent.com/1678001/153722121-17d3c6e5-4f81-4825-aa39-c68d2991b0ae.png)

**Comment by dsamuelis** [comment]
> I just had an idea regarding the "~50px above"... Does that change if the "Time Warp" (F8) panel is shown? ![image](https://user-images.githubusercontent.com/1678001/153722121-17d3c6e5-4f81-4825-aa39-c68d2991b0ae.png)

I cannot reproduce the issue anymore in 2.4. Seems to be gone! 

My test case with Simairport (likely resetting OpenGL)/Chrome (perhaps poisoning OpenGL) from ~10 posts above also does not trigger the vertical offset anymore...

Similarly, the time warp bar does not trigger the issue.

[log.txt](https://github.com/qutescoop/qutescoop/files/8054300/log.txt)

**So far I can report flawless operation of 2.4**


Unfortunately I also cannot reproduce it anymore with 2.3 that I still have installed as well. Perhaps Chrome has fixed their behavior in the meantime?

**Comment by droesen** [comment]
Haven't come across the problem with 2.4.0 yet either.

**Comment by droesen** [comment]
OK, now having the problem again with v2.4.0. Restarting QS fixed it.

**Comment by dsamuelis** [comment]
V2.5 had vertical offsets for me during first start after installation. Works fine thereafter.

**Comment by jonaseberle** [comment]
I think we could make a test build where we log the received mouse coordinates to see if this goes wrong there or in OpenGL mouse coordinates->lat/lon mapping.

**Comment by dsamuelis** [comment]
> I think we could make a test build where we log the received mouse coordinates to see if this goes wrong there or in OpenGL mouse coordinates->lat/lon mapping.

I'm pretty certain that it is in the received mouse coordinates, otherwise the dependency of the issue with outside applications, that also work on the OpenGL layer, would not really be explicable? I haven't tried yet if I can find a switching condition with 2.5 as described in this post https://github.com/qutescoop/qutescoop/issues/46#issuecomment-1030801295

And yes of course, if you could do an instrumented version that can document mouse values, I'd gladly test and supply debug data!

**Comment by jonaseberle** [comment]
This build https://github.com/jonaseberle/qutescoop/releases/tag/v2.5.0-1-g31f1e71 will output the local widget coordinates and also the result after mapping to lat/lon on left mouse button click.

I would be interested if the reported widget height is correct and if clicks at the very top and bottom have plausible `y` values.
The reported widget height should change depending on a shown "Time Warp" (F8) panel. In my case it is 59px difference, but that depends on your system font and style.

**Comment by dsamuelis** [comment]
@jonaseberle Danke für die Debug-Version!

Dankenswerterweise ist die Issue gleich beim ersten Start von der instrumentierten Version wieder aufgetreten, Log anbei.

- Der vertikale Offset tritt sowohl bei aktivierter als auch bei desaktivierter Time Warp Bar auf, und hat die gleiche Größe
- Bei den letzten 6 oder 7 Klick-Testcases im Log habe ich immer direkt auf dem (magenta/schwarzen) Punkt vom Objekt angefangen zu klicken (ohne die Detailinformationen zu bekommen), habe den Cursor ein Stück nach oben geschoben, wieder geklickt, und so lange wiederholt, bis ich die Detailinformationen zum Objekt bekommen habe.

[log.txt](https://github.com/qutescoop/qutescoop/files/8110867/log.txt)

Als Beispiel:
Erster Klick direkt auf den schwarzen Punkt von LFRS:
2022-02-21T16:37:52.835Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=174, y=563], onGlobe=1, globe[lat=46.6432, lon=-1.49806]"

Zweiter Klick, immer noch keine Aktivierung von LFRS-Details
2022-02-21T16:37:53.435Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=172, y=556], onGlobe=1, globe[lat=46.7341, lon=-1.56417]"

Dritter
2022-02-21T16:37:54.027Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=172, y=543], onGlobe=1, globe[lat=46.9123, lon=-1.61209]"

Vierter Klick, hier gingen dann die Detailinformationen zu LFRS auf, ca. 1.5 Cursorlängen oberhalb vom Airport-Punkt:
2022-02-21T16:37:54.595Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=174, y=534], onGlobe=1, globe[lat=47.0409, lon=-1.60476]"

**Comment by dsamuelis** [comment]
Beim zweiten Start wieder alles normal. Log anbei, letzter Klick wieder auf den schwarzen Punkt LFRS bei gleicher Bildposition :)

[log.txt](https://github.com/qutescoop/qutescoop/files/8110939/log.txt)

2022-02-21T16:46:49.305Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=176, y=523], onGlobe=1, globe[lat=47.1969, lon=-1.60493]"

Irgendwie ist also beim ersten Start in der y-Koordinate ein Offset von 40px (schwarzer Punkt von LFRS auf 563, beim zweiten Start auf 523).

**Comment by jonaseberle** [comment]
Danke. 

Nur zur Referenz hier LFRS: `LFRS:Nantes Atlantique:Nantes:FR:47.15702057:-1.60780835`

Könntest Du mal bitte ganz oben und ganz unten klicken? Ist ganz oben dann `y=40`? Und ganz unten? `y=height+40`?

Und hier habe ich mal noch die globalen Mauskoordinaten und das Ergebnis einer anderen Umrechnung (`mapFromGlobal`) geloggt: https://github.com/jonaseberle/qutescoop/releases/tag/v2.5.0-1-g436121b - vielleicht bringt uns das weiter?

**Comment by dsamuelis** [comment]
Mit der 2.5.0-1, aber ohne Vertikaloffset: (oben links, rechts; unten links, rechts, LFRS)

2022-02-21T22:07:41.778Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=1, y=0], mapFromGlobal[x=1, y=0], global[x=201,y=44] onGlobe=1, globe[lat=53.7421, lon=-8.12141]"
2022-02-21T22:07:45.059Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=1719, y=1], mapFromGlobal[x=1719, y=1], global[x=1919,y=45] onGlobe=1, globe[lat=53.7287, lon=33.2563]"
2022-02-21T22:07:48.824Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=0, y=956], mapFromGlobal[x=0, y=956], global[x=200,y=1000] onGlobe=1, globe[lat=40.7584, lon=-3.46328]"
2022-02-21T22:07:52.682Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=1719, y=952], mapFromGlobal[x=1719, y=952], global[x=1919,y=996] onGlobe=1, globe[lat=40.8165, lon=28.6004]"
2022-02-21T22:07:55.900Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=167, y=515], mapFromGlobal[x=167, y=515], global[x=367,y=559] onGlobe=1, globe[lat=47.2829, lon=-1.81929]"
[log.txt](https://github.com/qutescoop/qutescoop/files/8112312/log.txt)



Mit der ersten Debug Version konnte ich ihn triggern, dabei war tatsächlich y etwa +30:

2022-02-21T22:04:13.328Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=10, y=31], onGlobe=1, globe[lat=53.3594, lon=-7.70246]"
2022-02-21T22:04:17.202Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=1721, y=33], onGlobe=1, globe[lat=53.2913, lon=33.0841]"
2022-02-21T22:04:20.248Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=8, y=987], onGlobe=1, globe[lat=40.3539, lon=-3.21202]"
2022-02-21T22:04:22.415Z [DBG] GLWidget::mouseReleaseEvent left btn before objectsAt() "widget[width=1720, height=959], event[x=1725, y=987], onGlobe=1, globe[lat=40.3155, lon=28.5917]"
[log.txt](https://github.com/qutescoop/qutescoop/files/8112324/log.txt)


Ich probiere noch ein paar Sachen, um den Offset mit der zweiten Debug-Version auch nochmal zu triggern :)

**Comment by dsamuelis** [comment]
Und wieder einmal, wenn man lange genug wartet, kommt die Issue doch wieder :)

Hier ein Log mit doch wieder präsentem vertikalem Offset und der zweiten Debug Version.
[log.txt](https://github.com/qutescoop/qutescoop/files/8205977/log.txt)

Und hier auch noch ein zweiter Start, ebenfalls noch mit vertikalem Offset. Hierbei habe ich auch nochmal in die Ecken vom Karten-Viewport geklickt.
[log.txt](https://github.com/qutescoop/qutescoop/files/8205995/log.txt)

Die Timewarp-Leiste hat weiterhin keinen Einfluss auf das Vorhandensein von der Issue.
RTX 2060 SUPER, Treiber NVidia 511.79 DCH

**Comment by jonaseberle** [comment]
Also anscheinend sind die Koordinaten, die uns bei den Mausevents [z.B. QGLWidget::mouseReleaseEvent](https://doc.qt.io/qt-5/qwidget.html#mouseReleaseEvent) übergeben werden, bei manchen Treibern nicht korrekt. Wir sehen in Deinem Log.txt, dass es (in Deinem Fall) einen Versatz (x +8, y +31) gibt.

Aber in Deinem Log sieht man auch, dass wir eine andere Funktion (`mapFromGlobal()`) benutzen können, um den Fehler wieder rauszurechnen. Die Funktion scheint für beide Fälle zu funktionieren. Ich mache mal eine Testversion damit.

Eigentlich müssten wir mehr Fehler-Reports dazu finden (Ich suche mit solchen Begriffen "Qt OpenGL Nvidia 511.79 mouseReleaseEvent mouseClickEvent mapFromGlobal mouse event coordinates").

**Comment by dsamuelis** [comment]
> Eigentlich müssten wir mehr Fehler-Reports dazu finden (Ich suche mit solchen Begriffen "Qt OpenGL Nvidia 511.79 mouseReleaseEvent mouseClickEvent mapFromGlobal mouse event coordinates").

Würde ich auch denken, eigentlich müsste das mehr Personen betreffen... insofern habe ich mich jetzt gerade Mausseitig nochmal auf die Suche gemacht. Ich habe in der Signalkette von Maus, Tastatur und Monitoren einen suspekten KVM-Switch Marke "PWAY HDMI KVM Switch 2 Port Dual Monitor". Mausseitig habe ich ihn gerade mal herausgenommen, ohne Effekt. Bildschirmseitig wäre das leider eine größere Umverkabelung, das würde ich mir gerne sparen. Vielleicht macht der irgendetwas merkwürdiges im Maus- oder HDMI-Signal... 

@droesen  bei Dir ist die gleiche Issue auch aufgetreten, besteht hier evtl eine Korrelation?

**Comment by jonaseberle** [comment]
Ich glaube nicht, dass Maus/Maustreiber etwas damit zu tun hat.
Ich mache heute Abend mal eine Testversion mit `mapFromGlobal`.

**Comment by droesen** [comment]
Ich glaube auch nicht daran - vor allem warum sollte das nur bei einer bestimmten Qt-Applikation, und das auch nicht immer, auftreten? Wenn da was bereits am Input-Device kaputt wäre, würde das auch den Desktop und andere Applikationen betreffen. Außerdem ist mein NVIDIA-Treiber deutlich älter (497.09). Aber ja, bei mir ist auch ein "smarter" KVM-Switch (Uniclass AL-602Q) im Spiel - wenn ich auch nicht denke das der irgendein Faktor ist.

**Comment by dsamuelis** [comment]
Ich suche nur nach hinreichend exotischen Dingen, die bei mir im Signalweg zwischen Maus, Rechner und Monitor sind und nicht bei jedem auftreten :) 

Und ich habe zumindest sporadisch in einer oder zwei Qt-Anwendungen auch schonmal merkwürdiges Verhalten im Zusammenhang mit Mausaktionen beobachtet, insofern mögen teilweise auch andere Anwendungen betroffen sein. 

Bei mir ist die Issue ja ebenfalls auch schon mit älterem Treiber aufgetreten (glaube auch 497.x)
