### ISSUE TITLE
[gathering input] Sector files // Remove firdisplay.sup? // vatspy-data-project

### ISSUE THREAD

**Issue by jonaseberle** [qutescoop/qutescoop#47]
![image](https://user-images.githubusercontent.com/1678001/152547334-ee261b1f-c281-43be-bbce-61a085aa5d2f.png)
I don't really know the rationale behind that option. How is [firdisplay.sup](https://github.com/qutescoop/qutescoop/blob/master/data/firdisplay.sup) used? Is it the "VATSIM" differences to the ICAO structure? Or were those the differences to the IVAO structure?
QuteScoop is VATSIM only now so could we merge it into [firdisplay.dat](https://github.com/qutescoop/qutescoop/blob/master/data/firdisplay.dat)?

I hope @FlyingFoxVATSIM @ogruetzmann @diibify might be knowledgeable about that.

Partly unrelated, but I would like to start the conversation with you sector file folks: There is [vatspy-data-project](https://github.com/vatsimnetwork/vatspy-data-project) which has the [Sector coordinates as GeoJSON](https://github.com/vatsimnetwork/vatspy-data-project/blob/master/Boundaries.geojson).
It is an open and well-adopted standard and a multitude of editing software exists. Also I like that format because it is easy to add properties (for example the vertical extent for sectors) in the future.
How do you feel about it? 
Where is all this going and will we have a global database with proper sector ownership cleverness like EuroScope once? http://files.aero-nav.com/ looks pretty "global" already - is that data somehow interesting for us?
What happened to http://www.euroscope.hu/sectorfile/euroscope_sector_providers.txt? At least VATITA and EDGG I know of don't use that mechanism any more. Is that the general trend? It looked really great 8 years ago.

**Comment by ogruetzmann** [comment]
That's indeed the Vatsim differences. Not sure how it used to work, though

**Comment by jonaseberle** [comment]
I just thought that we had information about it... and yes we did 
https://github.com/qutescoop/qutescoop/blob/e586b0899dab6eb4dcae0afe3b2b6a285dce61be/data/_notes.txt#L116-L121
But that `data/_notes.txt` info file was deleted in https://github.com/qutescoop/qutescoop/commit/2aad575ea28ab2c5ff4db047336ce9e39b66a225 (I've [re-added](https://github.com/qutescoop/qutescoop/blob/master/data/_notes.txt) it).

So I take it that we could merge firdisplay.sup into firdisplay.dat?

**Comment by jonaseberle** [comment]
Heads up: 
It seems we do not need `firlist.dat`'s lat/lng any more (https://github.com/qutescoop/qutescoop/issues/52).
We are drawing _CTR/_FSS labels in the middle of the sector anyways now since the new VATSIM status feed does not contain controller viewcenters any more.
