### ISSUE TITLE
RU-ERC_FSS label not shown

### ISSUE THREAD

**Issue by jonaseberle** [qutescoop/qutescoop#52]
RU-ERC_FSS (Dal Control) is online but has no label:

![image](https://user-images.githubusercontent.com/1678001/152638206-d2d08485-f8f7-4409-9ddd-ba2ccae3e579.png)

I am not sure if this is just that sector, the fact that it is `_FSS` or the fact that it has a `-` in the callsign.

There is a proper label with "Show all sectors":
![image](https://user-images.githubusercontent.com/1678001/152638255-51db8fad-ecf6-41a3-b31b-6f15b47e5fea.png)

**Comment by Luca0208** [comment]
The sector does have a label, but it doesn't show in the correct spot.
![Screenshot from 2022-02-05 11-47-07](https://user-images.githubusercontent.com/9638292/152639131-dc91cdbe-46b4-44f2-b231-c17cb3f233a6.png)

(If anyone wants to test for themselves, I've uploaded some sample status files that can be served locally [here](https://gist.github.com/Luca0208/dd7b074fd317618586bb94a345927596))

Taking a quick look at the sector it seems like it contains the wrap-around of the longitude, which I presume confuses [this](https://github.com/qutescoop/qutescoop/blob/master/src/Sector.cpp#L72-L99).

Does the show all sector function get the placement of the label from somewhere else? If yes it would probably be better to check that data source first and only then fall back onto the center of the sector.

I'm gonna see if I can figure out the math to make the center calculation work.

**Comment by jonaseberle** [comment]
Oh, cool :) We had the same idea with providing a reproducible status in order to test later :)

I uploaded test fixtures to this repo:
Use user defined network: `https://raw.githubusercontent.com/qutescoop/qutescoop/master/tests/fixtures/issue-52/status.ini`

Github Gists are a great idea for users to upload the VATSIM status they have problems with. I think we could add that information to a Github ISSUE_TEMPLATE.

Great starting point to get debugging! I was actually chasing something else and will not pursue this problem now (just in case you plan to make a PR already - I have my mind somewhere else currently).

**Comment by jonaseberle** [comment]
Just one thought: We should use `->getCenter()` here, too:
https://github.com/qutescoop/qutescoop/blob/master/src/GLWidget.cpp#L1250-L1255

https://github.com/qutescoop/qutescoop/blob/master/src/BookedController.cpp#L76-L95

That will make it consistent and make sector file editing and debugging easier.

I think we can deprecate lat/lng in [firlist.dat](https://github.com/qutescoop/qutescoop/blob/master/data/firlist.dat) then and remove all usages in code.

**Comment by Luca0208** [comment]
I think I might've found a way to fix it, it's not the cleanest thing, however considering that [the alternative](https://skeptric.com/calculate-centroid-on-sphere/) seems to involve fixed-point iteration, I'd argue this is still the better way to solve it, if only for performance sake.

The changes are in [Luca0208/fix-center](https://github.com/Luca0208/qutescoop/tree/fix-center) however I'd like to see this get some testing first, before cleaning the code and creating a PR.
I've also changed the "Display all Sectors" to use `->getCenter()` however it creates a lot of overlap of the labels. The builds can be found here: See updated links below

I'd be happy for any feedback I can get on whether this creates problems with other sectors. If you do see any problems, if possible grab a copy of https://data.vatsim.net/v3/vatsim-data.json and attach it.

**Comment by jonaseberle** [comment]
Thank you!
I tested with https://github.com/Luca0208/qutescoop/actions/runs/1800265265

It fixes the RU-ERC_FSS label but it currently crashes when selecting "Display all sectors". Can you reproduce that?

**Comment by Luca0208** [comment]
> Can you reproduce that?

With the artifact yes, with my own compiled version no. Unfortunately I'm not gonna have a lot of time until Tuesday, so I won't be able to test any further until then.

**Comment by Luca0208** [comment]
Managed to reproduce the bug with my own compiled version.
It looks like one sector (NVVV) doesn't contain any points which caused the code to crashed, I've pushed a preliminary update. Builds: [Linux](https://github.com/Luca0208/qutescoop/actions/runs/1808696948), [Mac](https://github.com/Luca0208/qutescoop/actions/runs/1808696951), [Windows](https://github.com/Luca0208/qutescoop/actions/runs/1808696949)

**Comment by FlyingFoxVATSIM** [comment]
> It looks like one sector (NVVV) doesn't contain any points which caused the code to crashed, I've pushed a preliminary update.

Please check the attached updated files for Qutescoop. Indeed the airspace data for NVVV was missing and I just added it (from VatSpy Data Project).
[Update_Qutescoop_08FEB2022.zip](https://github.com/qutescoop/qutescoop/files/8019365/Update_Qutescoop_08FEB2022.zip)

**Comment by jonaseberle** [comment]
Thank you both. 
@Luca0208 that works very well.

@FlyingFoxVATSIM  We want resilient code anyways that does not crash on sector file problems so that was a welcome data flakyness ;)
And I am going to add your data file updates now (and I could talk you through making a Pull Request so you can take proper credit for your changes).

**Comment by jonaseberle** [comment]
Fixed by Luca :)
