### ISSUE TITLE
Streamline METARs

### ISSUE THREAD

**Issue by jonaseberle** [qutescoop/qutescoop#54]
I would like to make the METARs more useful. 

Here are my suggestions:

## Show them completely in the search list
![image](https://user-images.githubusercontent.com/1678001/152652826-566688e5-053b-4a19-9a4c-e22d47054675.png)

The upper panel could already show the complete METAR. At that size, that would be 2 or 3 lines high which is fine.

## The lower panel is then unnecessary
I know the "human translation" is nice sometimes if you don't know a used code from the METAR. But like that it always takes screen real estate.
I would be fine with removing it completely. But we could also open it in a little dialog box when clicking a METAR or on hover.

## We should show it in the airport window
That is where it would be most helpful I think. The current METAR search might be helpful if you are looking for an alternate or want to get the current "weather picture". But when in approach you usually have the destination Airport dialog open already.
I think it could nicely go here:
![image](https://user-images.githubusercontent.com/1678001/152653094-94ff46e5-a09f-49f1-aa71-0a767eae9a74.png)

## shown METARs could self-update
That would be just cool

**Comment by FlyingFoxVATSIM** [comment]
I suggest considering getting rid of the translation of raw METAR data to "plain text". I would hazard a guess that all users of Qutescoop know how to interpret METARs.

**Comment by jonaseberle** [comment]
Here's the first step:
![image](https://user-images.githubusercontent.com/1678001/152701488-3d67cf20-c147-445b-877d-e91e347c4bc6.png)

**Comment by jonaseberle** [comment]
I also had an idea where to put the "human" METAR translation:
![image](https://user-images.githubusercontent.com/1678001/152709930-df9cdddc-bb1a-46d1-92d9-416442001b7d.png)

Here is the METAR in the airport detail dialog:
![image](https://user-images.githubusercontent.com/1678001/152710103-568e29f3-b83c-47e5-b318-5f88f6b46ee9.png)

**Comment by jonaseberle** [comment]
[Here's a build](https://github.com/qutescoop/qutescoop/suites/5198532482/artifacts/158620488) that includes it.

**Comment by diibify** [comment]
One more small remark. As you can see on your screenshot, it would be great if the first line of the METARs pop up could show the airport name. Unfortunately, this is no longer the case at the moment.
![Screenshot 2022-02-16 100041](https://user-images.githubusercontent.com/16623471/154230596-47a585fc-8273-4d42-9367-8c496731cb2a.jpg)

**Comment by jonaseberle** [comment]
I removed that first line because I found it a bit superfluous:
```
Frankfurt-am-Main Weather Information, Recorded 16th on 0850z
Wind from 190 at 12KT
...
```

Do you think that should come back?

**Comment by diibify** [comment]
Yes, I see what you mean. And a left click opens the airport window anyway. 

The background is that yesterday, for example, I entered "LD" in the search and didn't know all the ICAO codes of the airports in the region coming up. It would have been nice to be able to look through the list of filtered airports and see which airport is behind the ICAO code.

**Comment by jonaseberle** [comment]
Yes, that makes sense because it is not only the METAR "decoder" but also the tooltip for the list items.

Let's put the airport name back in.

**Comment by jonaseberle** [comment]
This includes it:
https://github.com/qutescoop/qutescoop/releases/tag/v2.4.0-22-g353f67e
