### ISSUE TITLE
Time Warp field too small (2.3.0.-49, Windows)

### ISSUE THREAD

**Issue by diibify** [qutescoop/qutescoop#55]
Just a small optical error - the little box with the time warp is a bit too small, the minutes are cut off. 

![Time Warp](https://user-images.githubusercontent.com/16623471/152848035-763c0bc6-b8d7-4ced-857d-b89d16b11494.jpg)

**Comment by jonaseberle** [comment]
Thanks. I double checked if we use any custom settings. It's basically only the date format that is not default:
![image](https://user-images.githubusercontent.com/1678001/152855429-6cfef12b-1419-44f8-86f4-4fb2e520fb41.png)

It might be a Qt bug in which case we should check if there is already a bug report.

That's how I see it:
![image](https://user-images.githubusercontent.com/1678001/152854011-57142240-982b-4e0f-a5e0-ddb5c839e18d.png)

**Comment by diibify** [comment]
It is fixed for me. Shall we close here?

**Comment by jonaseberle** [comment]
Very nice. I don't remember having changed something in that area but I like self-healing bugs :)

**Comment by diibify** [comment]
Unfortunately, I am currently having the problem again. Am I the only one (Windows)?

**Comment by jonaseberle** [comment]
I'll just play around a bit with it:
https://github.com/jonaseberle/qutescoop/releases/tag/v2.4.0-13-g3e5e631
Could you see if one of those test fields works for you?

That's how it looks for me:
![image](https://user-images.githubusercontent.com/1678001/153924083-a7d817ee-1c28-4e56-9793-ce9b21e83600.png)

1) default
2) Horizontal Stretch: 1
3) Horizontal Policy: Prefered

**Comment by diibify** [comment]
![Screenshot 2022-02-14 195632](https://user-images.githubusercontent.com/16623471/153928310-4cb6e5c6-9f87-4781-a54f-d13978b1f92a.jpg)

**Comment by jonaseberle** [comment]
One more try:
https://github.com/jonaseberle/qutescoop/releases/tag/v2.4.0-15-gf9da5ed

![image](https://user-images.githubusercontent.com/1678001/153932332-480f4597-6a34-481b-a454-d7d00636bfac.png)

4) Horizontal Policy: Expanding
5) Horizontal Policy: MinimumExpanding
6) Horizontal Policy: Maximum
7) Custom Stylesheet: 15px padding on the right
8) Horizontal Policy: Maximum + Custom Stylesheet: 15px padding on the right

**Comment by diibify** [comment]
![Screenshot 2022-02-14 203810](https://user-images.githubusercontent.com/16623471/153934225-787d1b92-96f5-459e-aa49-fe4d39043ef5.jpg)

**Comment by jonaseberle** [comment]
Ok, I think we got it :) 
`Custom Stylesheet: 5px padding on the right` should be fine.

I guess you have the same problem with this field?
![image](https://user-images.githubusercontent.com/1678001/153934774-9cbc87af-6cc8-423b-ada1-f853e754d542.png)

**Comment by diibify** [comment]
Oh yes - I hadn't even noticed that
![Screenshot 2022-02-14 204324](https://user-images.githubusercontent.com/16623471/153934956-351e007a-2aae-491b-806b-3fcc02fa2bcd.jpg)
.
