### ISSUE TITLE
Navigation data folder selection (Windows)

### ISSUE THREAD

**Issue by diibify** [qutescoop/qutescoop#59]
The window to select the folder for the AIRAC only lets me select one file (on Windows). Clicking on this file and click "Open", it selects the directory. So everything is correct, but it's a bit unintuitive that you can't select the folder in the window
![Navigation_Database](https://user-images.githubusercontent.com/16623471/152990377-b279c6e1-31bb-4bd4-89d9-ffd74857f97d.jpg)
.

**Comment by jonaseberle** [comment]
If you hit "Öffnen" here it should select the folder.

But we can look into making that more clear.

**Comment by diibify** [comment]
When a directory is selected under Windows and I press "Öffnen", it only opens the directory for me. But it does not select it. I have to select a file.

**Comment by jonaseberle** [comment]
That dialog should really only show directories:
https://github.com/qutescoop/qutescoop/blob/3c8469e8496ec4be22f484922f69d855c0dd5e2c/src/PreferencesDialog.cpp#L492-L495

And for me on Linux (KDE) it also did that:
![image](https://user-images.githubusercontent.com/1678001/153013298-2bc1ecf7-be24-4851-8a3b-0dcf50c802c3.png)
I just select the directory that I set in the "Navigraph FMS Data Updater" there for X-Plane 10.

But maybe [this](https://github.com/qutescoop/qutescoop/commit/a7f5cc33bb606f78a7941750035e6a45eccc6b9b) change fixes it for Windows? Could you please try https://github.com/qutescoop/qutescoop/suites/5221267640/artifacts/160024948?

**Comment by diibify** [comment]
It does - thank you very much!

**Comment by jonaseberle** [comment]
Fantastic. Thank you for reporting and testing!
