### ISSUE TITLE
Recognize _CTR and _FSS suffixes with same airspace designator

### ISSUE THREAD

**Issue by FlyingFoxVATSIM** [qutescoop/qutescoop#6]
QT seems to be unable to differentiate between airspace designators, although they have different suffixes.
Example: on the Azores there are both LPPO_CTR (radar terminal control) and LPPO_FSS (oceanic control) with completely different airspace definitions. In firlist.dat they are currently defined as
LPPO_FSS:Santa Maria Radio:PT:33:-28:1837
LPPO_CTR:Santa Maria Radar:PT:39:-30:1838

![screenshot_sectorviewer](https://user-images.githubusercontent.com/66524946/84185954-11457a80-aa90-11ea-98eb-ea132c9de59e.jpg)

Now, when both LPPO_FSS and LPPO_CTR are online, QT cannot understand who is who and just draws a circle with the information "no sector data". If only LPPO_FSS is online, its airspace is displayed correctly.

If there's a way to make QT recognize suffixes to differentiate between stations, that would be really nice.

**Comment by jonaseberle** [comment]
I haven't worked on it yet, just added some reproducible test data.
Use "user defined network": https://raw.githubusercontent.com/qutescoop/qutescoop/master/tests/fixtures/issue-6/status.json

Our `firlist.dat`:
https://github.com/qutescoop/qutescoop/blob/1ec09002021be3d3baae2cb655cec257af20f38d/data/firlist.dat#L336-L337

Cross-referencing vatspy-data-project:

https://github.com/vatsimnetwork/vatspy-data-project/blob/23d56bfa55daeb6131d37a2e62665cbfa4c0c468/VATSpy.dat#L18036

https://github.com/vatsimnetwork/vatspy-data-project/blob/0fd02c828135aa3e6c679d5a681351d635930739/Boundaries.geojson?short_path=efc96a7#L204

I think both data formats don't cater for it yet, do they?

I basically like what you proposed with adding a specific suffix like `_CTR`. That should be taken then for all controller logins `LPPO_*CTR` (`LPPO_M_CTR`, `LPPO_X_CTR`, ...).

My current feeling is that it would be cleaner if we would clearly separate the prefix and the suffix we want to match.
For example by adding an optional further field like
`LPPO:Santa Maria Radar:PT:39:-30:1839:CTR`.

Or split the existing field into prefix / suffix by a character that's invalid in logins, e.g.
`LPPO/CTR:Santa Maria Radar:PT:39:-30:1839`.

Both might break old QuteScoop versions but I don't care much honestly.

**Comment by FlyingFoxVATSIM** [comment]
Wouldn't it be easier to have "CTR" as standard and omit the suffix, but only treat "_FSS" as something special that requires adding this suffix?

**Comment by jonaseberle** [comment]
Sure. Depending on the station it might be more practical to use
```
LPPO/FSS:Santa Maria Radio:PT:33:-28:1838 
LPPO:Santa Maria Radar:PT:39:-30:1839
```

PS: Some day I'd like to have at least vertical extents as well for sectors...

**Comment by jonaseberle** [comment]
Will be fixed in next version
![image](https://github.com/qutescoop/qutescoop/assets/1678001/f0bce005-ebdd-42cd-977e-65030408c857)
