### ISSUE TITLE
HIghlight circles become thicker when plot route 

### ISSUE THREAD

**Issue by diibify** [qutescoop/qutescoop#61]
If you have (at least one) "plot route" displayed, the highlight circles of the friends list become thicker. If you switch off all "plot route" again, the circle becomes thin again (to the set thickness). 

But - priority at the very bottom... ;)

**Comment by jonaseberle** [comment]
I remember your graphics card ;)
```
GL_RENDERER NVIDIA: GeForce GTX 1060 6GB/PCIe/SSE2
GL_VERSION: 4.6.0 NVIDIA 511.65
```

Does any of this have any effect on the outcome?
![image](https://user-images.githubusercontent.com/1678001/153465076-a42c0275-1442-4e31-a8a6-8c1c37b72141.png)

**Comment by jonaseberle** [comment]
Also friend list/graphics related: https://github.com/qutescoop/qutescoop/issues/64.

**Comment by diibify** [comment]
Yes, it has. Also #64  "highlight circle" in friends list.
