### ISSUE TITLE
Alias in the friendslist

### ISSUE THREAD

**Issue by diibify** [qutescoop/qutescoop#62]
Since it is now permitted to be online at VATSIM without a name, I wanted to suggest whether it might be possible to expand our friends list with an alias that you assign yourself, which can then be displayed in the list as an alternative. Unfortunately, some people are still only online with their ID, but I would still like to have them in the list.

Maybe you have other ideas or suggestions on how to get around the "problem".

**Comment by jonaseberle** [comment]
Let's continue the discussion about the details in the [pull request](https://github.com/qutescoop/qutescoop/pull/89) to get this in and make it intuitive - your input is highly appreciated.
