### ISSUE TITLE
Windows build folder name

### ISSUE THREAD

**Issue by droesen** [qutescoop/qutescoop#73]
Hi,

v2.4.0 release ZIP contains the main folder with name "DIST-win64" - this should be something prettier like "QuteScoop v2.4.0" or so.

**Comment by jonaseberle** [comment]
Thanks for noting that!

I remember noticing it but then I forgot to chase it.

We are using `Compress-Archive` (supposedly a PowerShell command) after I had problems with plain `zip`.
https://github.com/qutescoop/qutescoop/blob/v2.4.0/.github/workflows/build.yaml#L160-L161

I guess we would have to tell it to strip the initial folder.

Would that work?
```
mkdir ~/release
cd DIST-win64
Compress-Archive . ~/release/QuteScoop-2.4.0-win.zip
```

**Comment by Luca0208** [comment]
Similarly for the Linux version each file name has `./` prepended to it:
```
$ tar tzf QuteScoop-v2.4.0-linux.tgz | head -n 5
./
./platforms/
./platforms/libqxcb.so
./QuteScoop.desktop
./downloaded/
```
This is fine when extracting from a terminal, but shows up as a folder called "." in GUI Programs (Or at least in GNOME File Roller)

**Comment by jonaseberle** [comment]
I've removed the root dirs.

(Downloads are under under "Artifacts" of the linked pull request above - it is expected that the "artifact" in contrary to the release "assets", contains the release .zip inside a .zip)
