### ISSUE TITLE
Booked controller "until" not shown in controller detail

### ISSUE THREAD

**Issue by jonaseberle** [qutescoop/qutescoop#92]
![image](https://user-images.githubusercontent.com/1678001/154277549-888dd2ad-e079-4b60-932f-229dae97fb2f.png)

It's fine in the "Bookings..." dialog.

**Comment by Luca0208** [comment]
That's my fault, the problem is [here](https://github.com/qutescoop/qutescoop/blob/master/src/WhazzupData.cpp#L199-L200) (The parentheses are placed wrongly).

I'm gonna quickly create a PR to fix this
